update TPSD_USER_PRODUCT_RELEASE_REL set RELEASE_ID = 3004;
delete from TPSD_PRODUCT_RELEASE_ERROR where RELEASE_ID > 3004;
delete from TPSD_PRODUCT_RELEASE_RESOURCE_REL where RELEASE_ID > 3004;
delete from TPSD_PRODUCT_RELEASE_RESOURCE where RESOURCE_ID not in (select RESOURCE_ID from TPSD_PRODUCT_RELEASE_RESOURCE_REL);
delete from TPSD_PRODUCT_RELEASE where RELEASE_ID > 3004;