select CI.CONTACT_INVITATION_ID "id",UC.USERNAME "created by",
    CI.CREATED_ON "created on",U.USER_ID "user id",U.USERNAME "user",
    IU.USER_ID "invitation user id",IU.USERNAME "invitation user"
from TPSD_CONTACT_INVITATION_OUTGOING_USER CIOU
    inner join TPSD_CONTACT_INVITATION CI on CI.CONTACT_INVITATION_ID=CIOU.CONTACT_INVITATION_ID
    inner join TPSD_USER UC on UC.USER_ID=CI.CREATED_BY
    inner join TPSD_USER U on U.USER_ID=CIOU.USER_ID
    inner join TPSD_USER IU on IU.USER_ID=CIOU.INVITATION_USER_ID
order by CIOU.USER_ID asc,CI.CREATED_ON asc