select PRRR.RESOURCE_PATH
from TPSD_PRODUCT P
inner join TPSD_PRODUCT_RELEASE PR on PR.PRODUCT_ID=P.PRODUCT_ID
inner join TPSD_PRODUCT_RELEASE_RESOURCE_REL PRRR on PRRR.RELEASE_ID=PR.RELEASE_ID
inner join TPSD_PRODUCT_RELEASE_RESOURCE PRR on PRR.RESOURCE_ID=PRRR.RESOURCE_ID
where P.PRODUCT_NAME='OpheliaProduct' and PR.RELEASE_NAME='20070407-1629';