select A.ARTIFACT_UNIQUE_ID "id",A.CREATED_ON "created on",CBU.USERNAME "created by",TU.USERNAME "team member username"
from TPSD_ARTIFACT_TEAM_REL ATR
inner join TPSD_ARTIFACT A on A.ARTIFACT_ID=ATR.ARTIFACT_ID
inner join TPSD_USER TU on TU.USER_ID=ATR.USER_ID
inner join TPSD_USER CBU on CBU.USER_ID=A.CREATED_BY
where A.ARTIFACT_UNIQUE_ID = 'f53ad80a-3792-4894-8ffa-bc91c15365d3';