select PR.RELEASE_ID,PR.RELEASE_NAME,PR.RELEASE_OS,PR.RELEASE_DATE
from TPSD_PRODUCT P
inner join TPSD_PRODUCT_RELEASE PR on PR.PRODUCT_ID=P.PRODUCT_ID
where P.PRODUCT_NAME='OpheliaProduct'
order by PR.RELEASE_DATE desc;