select A.ARTIFACT_NAME "name",CV.CONTAINER_VERSION_ID "version",CVPT.PUBLISHED_ON "published on",U.JABBER_ID "published to",CVPT.RECEIVED_ON "received on"
from CONTAINER_VERSION_PUBLISHED_TO CVPT
inner join CONTAINER_VERSION CV on CV.CONTAINER_ID=CVPT.CONTAINER_ID and CV.CONTAINER_VERSION_ID=CVPT.CONTAINER_VERSION_ID
inner join ARTIFACT A on CV.CONTAINER_ID=A.ARTIFACT_ID
inner join PARITY_USER U on U.USER_ID=CVPT.USER_ID
where A.ARTIFACT_UNIQUE_ID='2ce66ba0-4382-4441-abdc-2cff1c20d1a9';