/*
 * Jan 20, 2006
 */
package com.thinkparity.browser.application.browser.display.avatar;

/**
 * @author raykroeker@gmail.com
 * @version 1.1
 */
public enum AvatarId {
    ADD_TEAM_MEMBER,BROWSER_INFO,BROWSER_LOGO,BROWSER_MAIN,BROWSER_SETTINGS,
    BROWSER_TITLE,CONFIRM_DIALOGUE,PLATFORM_LOGIN,SESSION_INVITE_PARTNER,
    RENAME_DIALOGUE,SESSION_MANAGE_CONTACTS,SESSION_SEARCH_PARTNER,
    SESSION_SEND_FORM,SESSION_SEND_VERSION,STATUS,USER_PROFILE
}
