/*
 * BrowserTitleMenu.java
 *
 * Created on July 30, 2006, 3:33 PM
 */

package com.thinkparity.browser.application.browser.display.avatar;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;

import javax.swing.JLabel;
import javax.swing.JPopupMenu;

import com.thinkparity.browser.Constants.Colors.Browser;
import com.thinkparity.browser.application.browser.component.MenuFactory;
import com.thinkparity.browser.application.browser.component.PopupItemFactory;
import com.thinkparity.browser.platform.action.ActionId;
import com.thinkparity.browser.platform.action.Data;

/**
 *
 * @author raymond@thinkparity.com
 */
public class MainTitleAvatarMenuPanel extends MainTitleAvatarAbstractPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /** The new label's popup menu. */
    private JPopupMenu newJPopupMenu;
    
    /** The popup menu item factory. */
    private final PopupItemFactory popupItemFactory;

    /** Creates new form BrowserTitleMenu */
    public MainTitleAvatarMenuPanel() {
        super("BrowserTitleMenu.MenuPanel");
        this.popupItemFactory = PopupItemFactory.getInstance();
        initComponents();
    }

    /**
     * @see javax.swing.JComponent#paintComponent(java.awt.Graphics)
     */
    @Override
    protected void paintComponent(final Graphics g) {
        super.paintComponent(g);
        final Graphics g2 = g.create();
        try {
            if(signUpJLabel.isVisible()) {
                g.setColor(Browser.MainTitle.SIGN_UP_BACKGROUND);
                final Point location = signUpJLabel.getLocation();
                final Dimension size = signUpJLabel.getSize();
                g.fillRoundRect(
                        location.x - 4, location.y - 2,
                        size.width + 8, size.height + 4,
                        4, 4);
            }
        }
        finally { g2.dispose(); }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel helpJLabel;
        javax.swing.JFrame jFrame1;
        javax.swing.JMenuBar mainJMenuBar1;
        javax.swing.JLabel newJLabel;
        javax.swing.JMenu newJMenu1;
        javax.swing.JLabel profileJLabel;
        javax.swing.JMenu profileJMenu1;
        javax.swing.JLabel spacerJLabel;

        jFrame1 = new javax.swing.JFrame();
        mainJMenuBar1 = new javax.swing.JMenuBar();
        newJMenu1 = new javax.swing.JMenu();
        profileJMenu1 = new javax.swing.JMenu();
        newJLabel = new javax.swing.JLabel();
        profileJLabel = new javax.swing.JLabel();
        helpJLabel = new javax.swing.JLabel();
        signUpJLabel = new javax.swing.JLabel();
        spacerJLabel = new javax.swing.JLabel();

        newJMenu1.setText("NewMenu");
        mainJMenuBar1.add(newJMenu1);

        profileJMenu1.setText("ProfileMenu");
        mainJMenuBar1.add(profileJMenu1);

        jFrame1.setJMenuBar(mainJMenuBar1);

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        newJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.New"));
        newJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newJLabelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newJLabelMouseReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        add(newJLabel, gridBagConstraints);

        profileJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.Profile"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(profileJLabel, gridBagConstraints);

        helpJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.Help"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(helpJLabel, gridBagConstraints);

        signUpJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.SignUp"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(signUpJLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(spacerJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void newJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseClicked
        if (null == newJPopupMenu) {
            newJPopupMenu = MenuFactory.createPopup();
            newJPopupMenu.add(popupItemFactory.createPopupItem(ActionId.CONTAINER_CREATE, new Data(0)));
            newJPopupMenu.add(popupItemFactory.createPopupItem(ActionId.CONTACT_CREATE_INCOMING_INVITATION, new Data(0)));
        }
        final Rectangle jLabelBounds = ((JLabel) evt.getSource()).getBounds();
        newJPopupMenu.show(this, jLabelBounds.x, jLabelBounds.y + jLabelBounds.height);
    }//GEN-LAST:event_newJLabelMouseClicked

    private void newJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseEntered
// TODO add your handling code here:
    }//GEN-LAST:event_newJLabelMouseEntered

    private void newJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseExited
// TODO add your handling code here:
    }//GEN-LAST:event_newJLabelMouseExited

    private void newJLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseReleased
        
    }//GEN-LAST:event_newJLabelMouseReleased
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel signUpJLabel;
    // End of variables declaration//GEN-END:variables
}
