/*
 * SessionSendFormAvatar.java
 *
 * Created on March 14, 2006, 9:54 AM
 */

package com.thinkparity.browser.application.browser.display.avatar;

import java.util.Collection;
import java.util.LinkedList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

import com.thinkparity.codebase.assertion.Assert;

import com.thinkparity.browser.application.browser.BrowserConstants;
import com.thinkparity.browser.application.browser.component.ButtonFactory;
import com.thinkparity.browser.application.browser.component.CheckBoxFactory;
import com.thinkparity.browser.application.browser.component.LabelFactory;
import com.thinkparity.browser.application.browser.component.ListFactory;
import com.thinkparity.browser.application.browser.component.ScrollPaneFactory;
import com.thinkparity.browser.application.browser.component.SeparatorFactory;
import com.thinkparity.browser.application.browser.display.avatar.session.UserListCellRenderer;
import com.thinkparity.browser.application.browser.display.provider.CompositeFlatSingleContentProvider;
import com.thinkparity.browser.model.util.ArtifactUtil;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;
import com.thinkparity.browser.platform.util.SwingUtil;

import com.thinkparity.model.parity.ParityException;
import com.thinkparity.model.parity.model.artifact.ArtifactModel;
import com.thinkparity.model.parity.model.document.Document;
import com.thinkparity.model.xmpp.JabberId;
import com.thinkparity.model.xmpp.JabberIdBuilder;
import com.thinkparity.model.xmpp.contact.Contact;
import com.thinkparity.model.xmpp.user.User;

/**
 *
 * @author  raymond
 */
public class SessionSendFormAvatar extends Avatar {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /**
     * The contacts list model.
     *
     */
    private final DefaultListModel contactsModel;

    /**
     * The contacts list selection model.
     *
     */
    private final DefaultListSelectionModel contactsSelectionModel;

    /**
	 * Flag indicating whether or not the include key checkbox is selected.
	 * 
	 * @see #includeKeyJCheckBoxStateChanged(javax.swing.event.ChangeEvent)
	 */
	private Boolean includeKeyIsSelected = Boolean.FALSE;

    /**
     * The team list model.
     *
     */
    private final DefaultListModel teamModel;

    /**
     * The team list selection model.
     *
     */
    private final DefaultListSelectionModel teamSelectionModel;

    /**
     * Used by the contact provider to exclude team members from the contact
     * list.
     *
     */
    private User[] team;

    /**
     * Create a SessionSendFormAvatar
     *
     */
    public SessionSendFormAvatar() {
		super("SessionSendForm", BrowserConstants.DIALOGUE_BACKGROUND);
		this.contactsModel = new DefaultListModel();
		this.contactsSelectionModel = new DefaultListSelectionModel();
		this.teamModel = new DefaultListModel();
		this.teamSelectionModel = new DefaultListSelectionModel();
		initComponents();
	}

    public void setState(final State state) {}

    public State getState() { return null; }

    public AvatarId getId() { return AvatarId.SESSION_SEND_FORM; }

    /**
     * Determine whether or not the user's input is valid.
     *
     */
    public Boolean isInputValid() {
		Long documentId;
		try { documentId = extractDocumentId(); }
		catch(final Throwable t) { return Boolean.FALSE; }

		Collection<Contact> contacts = null;
		try { contacts = extractTeam(); }
		catch(final Throwable t) { return Boolean.FALSE; }

		try { contacts.addAll(extractContacts()); }
		catch(final Throwable t) { return Boolean.FALSE; }

		final Boolean doIncludeKey = extractDoIncludeKey();
		if(doIncludeKey) {
			// only 1 user if the key is to be included
			if(1 != contacts.size()) { return Boolean.FALSE; }
		}
		else {
			// at least 1 user if the key is not included
			if(1 > contacts.size()) { return Boolean.FALSE; }
		}

		if(null != documentId && 0 < contacts.size()) {
			return Boolean.TRUE;
		}
		else { return Boolean.FALSE; }
	}

    /**
     * Reload the avatar based upon the input and content providers.
     *
     */
    public void reload() {
    	reloadDocument();
		reloadIncludeKey();
		reloadTeamMembers();
		reloadContacts();
		reloadSendJButtonState();

		includeKeyJCheckBox.requestFocusInWindow();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton cancelJButton;
        javax.swing.JLabel contactsJLabel;
        javax.swing.JScrollPane contactsJScrollPane;
        javax.swing.JLabel documentJLabel;
        javax.swing.JSeparator jSeparator_1;
        javax.swing.JLabel teamJLabel;
        javax.swing.JScrollPane teamJScrollPane;

        documentJLabel = LabelFactory.create(getString("DocumentLabel"));
        includeKeyJCheckBox = CheckBoxFactory.create(getString("IncludeKeyCheckBox"));
        jSeparator_1 = SeparatorFactory.create();
        sendToJPanel = new javax.swing.JPanel();
        teamJLabel = LabelFactory.create(getString("TeamLabel"));
        contactsJLabel = LabelFactory.create(getString("ContactsLabel"));
        teamJScrollPane = ScrollPaneFactory.create();
        teamJList = ListFactory.create();
        contactsJScrollPane = ScrollPaneFactory.create();
        contactsJList = ListFactory.create();
        sendJButton = ButtonFactory.create(getString("SendButton"));
        cancelJButton = ButtonFactory.create(getString("CancelButton"));
        vSpacerJLabel = LabelFactory.create();
        documentNameJLabel = new javax.swing.JLabel();

        includeKeyJCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        includeKeyJCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        includeKeyJCheckBox.setOpaque(false);
        includeKeyJCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent e) {
                includeKeyJCheckBoxStateChanged(e);
            }
        });

        sendToJPanel.setOpaque(false);

        teamJList.setCellRenderer(new UserListCellRenderer());
        teamJList.setModel(teamModel);
        teamJList.setSelectionModel(teamSelectionModel);
        teamJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                teamJListValueChanged(e);
            }
        });

        teamJScrollPane.setViewportView(teamJList);

        contactsJList.setCellRenderer(new UserListCellRenderer());
        contactsJList.setModel(contactsModel);
        contactsJList.setSelectionModel(contactsSelectionModel);
        contactsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                contactsJListValueChanged(e);
            }
        });

        contactsJScrollPane.setViewportView(contactsJList);

        org.jdesktop.layout.GroupLayout sendToJPanelLayout = new org.jdesktop.layout.GroupLayout(sendToJPanel);
        sendToJPanel.setLayout(sendToJPanelLayout);
        sendToJPanelLayout.setHorizontalGroup(
            sendToJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sendToJPanelLayout.createSequentialGroup()
                .add(sendToJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(teamJLabel)
                    .add(teamJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sendToJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(contactsJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(contactsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
        );
        sendToJPanelLayout.setVerticalGroup(
            sendToJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sendToJPanelLayout.createSequentialGroup()
                .add(sendToJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamJLabel)
                    .add(contactsJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sendToJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(teamJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .add(contactsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap())
        );

        sendJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                sendJButtonActionPerformed(e);
            }
        });

        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cancelJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sendJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(vSpacerJLabel)
                    .add(jSeparator_1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(sendToJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(documentJLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(includeKeyJCheckBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .add(documentNameJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(documentJLabel)
                    .add(documentNameJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(includeKeyJCheckBox)
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(vSpacerJLabel)
                    .add(jSeparator_1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sendToJPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelJButton)
                    .add(sendJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendJButtonActionPerformed
    	if(isInputValid()) {
			final Long documentId = extractDocumentId();
			final List<User> contacts = proxy(extractTeam());
			contacts.addAll(proxy(extractContacts()));
			final Boolean doIncludeKey = extractDoIncludeKey();
			toggleVisualFeedback(Boolean.TRUE);
			try {
				if(doIncludeKey) {
					// create a version and send it
					// update the server key holder
					final User user = contacts.get(0);
					// TODO Refactor the user object.
					final JabberId jabberId = JabberIdBuilder.parseUsername(user.getSimpleUsername());
					getArtifactModel().sendKey(documentId, jabberId);
				}
				else {
                    getDocumentModel().publish(documentId);

//                  // if the user is the key holder; we send the working version
//                  // otherwise we send the latest version
//                  if(ArtifactUtil.isKeyHolder(documentId)) {
//                      getSessionModel().send(contacts, documentId);
//                  }
//                  else {
//                      final DocumentVersion latestVersion =
//                          getDocumentModel().readLatestVersion(documentId);
//                      getSessionModel().send(contacts, documentId, latestVersion.getVersionId());
//                  }
				}
				// NOTE Interesting
				ArtifactModel.getModel().applyFlagSeen(documentId);
			}
			catch(final ParityException px) { throw new RuntimeException(px); }
			finally {
				toggleVisualFeedback(Boolean.FALSE);
				getController().fireDocumentUpdated(documentId);
				disposeWindow();
			}
		}
    }//GEN-LAST:event_sendJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
		disposeWindow();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void disposeWindow() {
    	SwingUtilities.getWindowAncestor(this).dispose();
    }

    private void includeKeyJCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_includeKeyJCheckBoxStateChanged
		if(includeKeyIsSelected != includeKeyJCheckBox.isSelected()) {
			if(includeKeyJCheckBox.isSelected()) {
				// since include key is selected; only 1 user can be used
				// as the "destination"  remove *all* but the first selected
				// user
				final int[] teamIndices = teamJList.getSelectedIndices();
                if(1 < teamIndices.length) {
					for(int i = 1; i < teamIndices.length; i++) {
						teamSelectionModel.removeSelectionInterval(i, i);
					}
					contactsSelectionModel.clearSelection();
				}
                else {
                    final int[] contactIndices = contactsJList.getSelectedIndices();
                    if(0 < teamIndices.length && 0 < contactIndices.length) {
                        contactsSelectionModel.clearSelection();
                    }
                }

                final int[] contactIndices = contactsJList.getSelectedIndices();
                if(1 < contactIndices.length) {
    				for(int i = 1; i < contactIndices.length; i++) {
    					contactsSelectionModel.removeSelectionInterval(i, i);
    				}
    			}

                contactsSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                teamSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
			}
			else {
				contactsSelectionModel.setSelectionMode(
						ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
				teamSelectionModel.setSelectionMode(
						ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
			}
		}
		includeKeyIsSelected = includeKeyJCheckBox.isSelected();
    	reloadSendJButtonState();
    }//GEN-LAST:event_includeKeyJCheckBoxStateChanged
    
    private void contactsJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_contactsJListValueChanged
    	if(!evt.getValueIsAdjusting()) {
			if(ListSelectionModel.SINGLE_SELECTION ==
				contactsSelectionModel.getSelectionMode()) {
				teamSelectionModel.clearSelection();
			}
		}
    	reloadSendJButtonState();
    }//GEN-LAST:event_contactsJListValueChanged
    
    private void teamJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_teamJListValueChanged
    	if(!evt.getValueIsAdjusting()) {
			if(ListSelectionModel.SINGLE_SELECTION ==
				teamSelectionModel.getSelectionMode()) {
				contactsSelectionModel.clearSelection();
			}
		}
    	reloadSendJButtonState();
    }//GEN-LAST:event_teamJListValueChanged

    /**
     * Extract the selected contacts.
     *
     */
    private List<Contact> extractContacts() {
		return SwingUtil.extract(contactsJList);
	}

    /**
     * Extract the doIncludeKey setting.
     *
     */
    private Boolean extractDoIncludeKey() {
		return includeKeyJCheckBox.isSelected();
	}

    /**
     * Extract the document id we are sending.
     *
     */
    private Long extractDocumentId() { return (Long) input; }

    /**
     * Extract the selected team.
     *
     */
    private List<Contact> extractTeam() { return SwingUtil.extract(teamJList); }

    /**
     * Obtain a list of contacts from the content provider.
     *
     */
    private Contact[] getContacts(final User[] team) {
		return (Contact[]) ((CompositeFlatSingleContentProvider) contentProvider)
				.getElements(0, team);
	}

    /**
	 * Obtain the document from the content provider.
	 * 
	 * @return The document.
	 */
    private Document getDocument() {
    	return (Document) ((CompositeFlatSingleContentProvider) contentProvider)
    		.getElement(0, (Long) input);
    }

    /**
     * Obtain a list of team members from the content provider.
     *
     */
    private User[] getTeam() {
		return (Contact[]) ((CompositeFlatSingleContentProvider) contentProvider)
				.getElements(1, (Long) input);
	}

    /**
     * Load a list model with the user list.
     *
     */
    private void loadUserList(final DefaultListModel listModel,
			final User[] users) {
		for (final User user : users) {
			logger.debug("Adding user:  " + user.getSimpleUsername());
			listModel.addElement(user);
		}
	}

	/**
	 * Proxy a contact list to a user list.
	 * 
	 * @param i
	 *            The contact list.
	 * @return The user list.
	 * @deprecated
	 */
	private List<User> proxy(final Iterable<Contact> i) {
		final List<User> l = new LinkedList<User>();
		for(final Contact c : i ) { l.add(c); }
		return l;
	}

    /**
     * Reload the contacts model.
     *
     */
    private void reloadContacts() {
		contactsModel.clear();
		if(null != input) loadUserList(contactsModel, getContacts(team));
	}

    /**
     * Reload the document.
     *
     */
    private void reloadDocument() {
    	documentNameJLabel.setText(getString("DocumentNameLabel.Empty"));
    	if(null != input) {
    		final Document document = getDocument();
    		final Object[] arguments = new Object[] {document.getName()};
    		documentNameJLabel.setText(getString("DocumentNameLabel", arguments));
    	}
    }

    /**
     * Reload the include key model.
     *
     */
    private void reloadIncludeKey() {
        includeKeyJCheckBox.setSelected(false);
		includeKeyJCheckBox.setVisible(false);
		if(null != input) {
			final Boolean isKeyHolder = ArtifactUtil
					.isKeyHolder(extractDocumentId());
			includeKeyJCheckBox.setVisible(isKeyHolder);
		}
	}

    /**
     * Set the enabled property of the send button based upon the validity
     * of the form's input.
     *
     */
    private void reloadSendJButtonState() {
    	sendJButton.setEnabled(isInputValid());
    }

    private void reloadTeamMembers() {
        teamModel.clear();
        if(null != input) {
            team = getTeam();
            loadUserList(teamModel, team);
        }
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#setInput(java.lang.Object)
     *
     */
    public void setInput(Object input) {
        Assert.assertNotNull("Cannot set null input:  " + getId(), input);
        this.input = input;
        reload();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList contactsJList;
    private javax.swing.JLabel documentNameJLabel;
    private javax.swing.JCheckBox includeKeyJCheckBox;
    private javax.swing.JButton sendJButton;
    private javax.swing.JPanel sendToJPanel;
    private javax.swing.JList teamJList;
    private javax.swing.JLabel vSpacerJLabel;
    // End of variables declaration//GEN-END:variables
    
}
