/*
 * ErrorDialog.java
 *
 * Created on July 21, 2006, 12:08 PM
 */

package com.thinkparity.browser.platform.application.dialog;

import javax.swing.SwingUtilities;

import com.thinkparity.browser.application.browser.BrowserConstants;
import com.thinkparity.browser.application.browser.component.TextFactory;
import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.platform.action.Data;
import com.thinkparity.browser.platform.application.dialog.ConfirmDialog.DataKey;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;

/**
 *
 * @author  Administrator
 */
public class ErrorDialog extends Avatar {
    
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /** Creates new form ErrorDialog */
    public ErrorDialog() {
        super("ErrorDialog", BrowserConstants.DIALOGUE_BACKGROUND);
        initComponents();
    }

    public void setState(final State state) {
    }

    public State getState() {
        return null;
    }

    public AvatarId getId() {
        return AvatarId.ERROR_DIALOGUE;
    }
    
    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#reload()
     * 
     */
    public void reload() {
        errorMessageJTextArea.setText("");
        if(null != input) {
            errorMessageJTextArea.setText(getString(
                    getErrorMessageKey(),
                    getErrorMessageArguments()));
        }
        okJButton.requestFocusInWindow();
    }
    
    /**
     * Obtain the error message key from the input data.
     * 
     * @return The error message key.
     */
    private String getErrorMessageKey() {
        return (String) ((Data) input).get(DataKey.MESSAGE_KEY);
    }
    
    /**
     * Obtain the error arguments from the input data.
     * 
     * @return The error message arguments.
     */
    private Object[] getErrorMessageArguments() {
        return (Object[]) ((Data) input).get(DataKey.MESSAGE_ARGUMENTS);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        okJButton = new javax.swing.JButton();
        errorMessageJTextArea = TextFactory.createArea();

        okJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("ErrorDialog.Ok"));
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        errorMessageJTextArea.setColumns(20);
        errorMessageJTextArea.setEditable(false);
        errorMessageJTextArea.setLineWrap(true);
        errorMessageJTextArea.setRows(5);
        errorMessageJTextArea.setWrapStyleWord(true);
        errorMessageJTextArea.setBorder(null);
        errorMessageJTextArea.setFocusable(false);
        errorMessageJTextArea.setOpaque(false);
        errorMessageJTextArea.setBorder(null);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(okJButton)
                    .add(errorMessageJTextArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(errorMessageJTextArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(okJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_okJButtonActionPerformed
    
    /**
     * Dispose of the window.
     */
    private void disposeWindow() {
        SwingUtilities.getWindowAncestor(this).dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea errorMessageJTextArea;
    private javax.swing.JButton okJButton;
    // End of variables declaration//GEN-END:variables
    
    /** Data keys. */
    public enum DataKey { MESSAGE_KEY, MESSAGE_ARGUMENTS }   
}
