/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil */

#ifndef _Included_com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil
#define _Included_com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: loaded */
/* Inaccessible static: LOGGER */
/*
 * Class:     com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil
 * Method:    CreateRectRgn
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil_CreateRectRgn
  (JNIEnv*, jobject, jint, jint, jint, jint);

/*
 * Class:     com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil
 * Method:    CreateRoundRectRgn
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil_CreateRoundRectRgn
  (JNIEnv*, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil
 * Method:    GetWindowHandle
 * Signature: (Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil_GetWindowHandle
  (JNIEnv*, jobject, jobject);

/*
 * Class:     com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil
 * Method:    SetWindowRgn
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_com_thinkparity_ophelia_browser_util_window_win32_Win32WindowUtil_SetWindowRgn
  (JNIEnv*, jobject, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
