/*
 * Created On: October 6, 2006, 1:42 PM
 */
package com.thinkparity.ophelia.browser.application.browser.display.avatar.tab;

import java.awt.Component;
import java.awt.GridBagConstraints;

import javax.swing.DefaultListModel;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

import com.thinkparity.codebase.log4j.Log4JWrapper;
import com.thinkparity.ophelia.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.ophelia.browser.application.browser.display.renderer.tab.DefaultTabPanel;

/**
 *
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class TabPanelAvatar<T extends TabModel> extends TabAvatar<T> {

    /** An apache logger. */
    private final Log4JWrapper logger;

    /** The filler constraints. */
    private final GridBagConstraints fillConstraints;

    /** The panel constraints. */
    private final GridBagConstraints panelConstraints;

    /** Creates new form TabPanelAvatar */
    public TabPanelAvatar(final AvatarId id, final T model) {
    	super(id, model);
        this.fillConstraints = new GridBagConstraints();
        this.fillConstraints.fill = GridBagConstraints.BOTH;
        this.fillConstraints.weightx = 1.0F;
        this.fillConstraints.weighty = 1.0F;
        this.fillConstraints.gridx = 0;
        this.fillConstraints.gridy = GridBagConstraints.RELATIVE;
        this.logger = new Log4JWrapper(super.logger);
        this.panelConstraints = new GridBagConstraints();
        this.panelConstraints.fill = GridBagConstraints.BOTH;
        this.panelConstraints.gridx = 0;
    	installDataListener();
        initComponents();
    }

    /**
	 * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#reload()
	 */
    @Override
	public void reload() {
    	super.reload();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        headerJLabel = new javax.swing.JLabel();
        tabJScrollPane = new javax.swing.JScrollPane();
        tabJPanel = new javax.swing.JPanel();
        fillJLabel = new javax.swing.JLabel();

        headerJLabel.setText(" ");

        tabJScrollPane.setBorder(null);
        tabJPanel.setLayout(new java.awt.GridBagLayout());

        tabJPanel.setOpaque(false);
        tabJPanel.add(fillJLabel, new java.awt.GridBagConstraints());

        tabJScrollPane.setViewportView(tabJPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, tabJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .add(headerJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(headerJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tabJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Install the a data listener on the list model. This will translate the
     * model's data events into UI component events.
     * 
     */
    private void installDataListener() {
        final DefaultListModel listModel = model.getListModel();
        listModel.addListDataListener(new ListDataListener() {
            public void contentsChanged(final ListDataEvent e) {
            }
            public void intervalAdded(final ListDataEvent e) {
                final int index0 = e.getIndex0();
                debug();
                tabJPanel.remove(fillJLabel);
                for (int i = index0; i < tabJPanel.getComponentCount(); i++) {
                    tabJPanel.remove(i);
                }
                for (int i = index0; i < listModel.size(); i++) {
                    panelConstraints.gridy = i;
                    tabJPanel.add((DefaultTabPanel) listModel.getElementAt(i), panelConstraints.clone(), i);
                }
                tabJPanel.add(fillJLabel, fillConstraints);
                tabJPanel.revalidate();
                tabJScrollPane.revalidate();
                revalidate();
                debug();
            }
            public void intervalRemoved(final ListDataEvent e) {
                final int index0 = e.getIndex0();
                final int index1 = e.getIndex1();
                debug();
                tabJPanel.remove(fillJLabel);
                for (int i = index0; i < index1 + 1; i++) {
                    tabJPanel.remove(i);
                }
                tabJPanel.add(fillJLabel, fillConstraints);
                tabJPanel.revalidate();
                tabJScrollPane.revalidate();
                revalidate();
                debug();
            }
        });
    }

    /**
     * @see com.thinkparity.codebase.swing.AbstractJPanel#debug()
     */
    @Override
    public void debug() {
        final Component[] components = tabJPanel.getComponents();
        logger.logDebug("{0} components.", components.length);
        for (final Component component : components) {
            logger.logVariable("component", component);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fillJLabel;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JPanel tabJPanel;
    private javax.swing.JScrollPane tabJScrollPane;
    // End of variables declaration//GEN-END:variables
}
