/*
 * WindowTitle.java
 *
 * Created on October 29, 2006, 4:11 PM
 */

package com.thinkparity.ophelia.browser.platform.application.window;

import java.awt.Graphics;
import java.awt.Graphics2D;

import javax.swing.Icon;
import javax.swing.SwingUtilities;

import com.thinkparity.codebase.swing.AbstractJPanel;

import com.thinkparity.ophelia.browser.Constants.Colors;
import com.thinkparity.ophelia.browser.Constants.Images;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.util.ImageIOUtil;

/**
 *
 * @author  Administrator
 */
public class WindowTitle extends AbstractJPanel implements WindowTitleButtons {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** Close label icon when disabled. */
    private static final Icon CLOSE_DISABLED_ICON = ImageIOUtil.readIcon("BrowserTitle_CloseDisabled.png");

    /** Close label icon. */
    private static final Icon CLOSE_ICON = ImageIOUtil.readIcon("BrowserTitle_Close.png");

    /** Close label rollover icon. */
    private static final Icon CLOSE_ROLLOVER_ICON = ImageIOUtil.readIcon("BrowserTitle_CloseRollover.png");

    /** The border type. */
    private BorderType borderType = BorderType.DEFAULT;

    /** The enabled flag for the close button. */
    private Boolean closeButtonEnabled;

    /** Creates new form WindowTitle */
    public WindowTitle() {
        closeButtonEnabled = Boolean.TRUE;
        initComponents();
        setTitleText(null);
    }

    /** Creates new form WindowTitle */
    public WindowTitle(final String title) {
        closeButtonEnabled = Boolean.TRUE;
        initComponents();
        setTitleText(title);
    }

    /**
     * @see com.thinkparity.ophelia.browser.platform.application.window.WindowTitleButtons#setCloseButtonEnabled(java.lang.Boolean)
     */
    public void setCloseButtonEnabled(final Boolean closeButtonEnabled) {
        this.closeButtonEnabled = closeButtonEnabled;
        setCloseButtonIcon();
    }

    /**
     * Set the border type. This affects painting on top left and top right.
     * 
     * @param borderType
     *            The border type.           
     */
    public void setBorderType(final BorderType borderType) {
        this.borderType = borderType;
    }

    /**
     * Set the title text.
     * 
     * @param title
     *            The title text.           
     */
    public void setTitleText(final String title) {
        titleJLabel.setText(title);
    }

    /** @see javax.swing.JComponent#paintComponent(java.awt.Graphics) */
    protected void paintComponent(final Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        try {
            // draw background image
            g2.drawImage(Images.Browser.Window.WINDOW_TITLE, 0, 0, this);

            // line on the bottom
            g2.setPaint(Colors.Browser.Window.TITLE_BOTTOM_LINE);
            g2.drawLine(0, getHeight()-1, getWidth()-1, getHeight()-1);

            // These images put borders on rounded corners.
            if (borderType == BorderType.WINDOW_BORDER2) {
                g.drawImage(Images.BrowserTitle.SYSTEM_DIALOG_TOP_LEFT_INNER,
                        0,
                        0,
                        Images.BrowserTitle.SYSTEM_DIALOG_TOP_LEFT_INNER.getWidth(),
                        Images.BrowserTitle.SYSTEM_DIALOG_TOP_LEFT_INNER.getHeight(), this);
                g.drawImage(Images.BrowserTitle.SYSTEM_DIALOG_TOP_RIGHT_INNER,
                        getSize().width - Images.BrowserTitle.SYSTEM_DIALOG_TOP_RIGHT_INNER.getWidth(),
                        0,
                        Images.BrowserTitle.SYSTEM_DIALOG_TOP_RIGHT_INNER.getWidth(),
                        Images.BrowserTitle.SYSTEM_DIALOG_TOP_RIGHT_INNER.getHeight(), this);
            } else {
                g2.drawImage(Images.BrowserTitle.DIALOG_TOP_LEFT,
                        0,
                        0,
                        Images.BrowserTitle.DIALOG_TOP_LEFT.getWidth(),
                        Images.BrowserTitle.DIALOG_TOP_LEFT.getHeight(), this);
                g2.drawImage(Images.BrowserTitle.DIALOG_TOP_RIGHT,
                        getWidth() - Images.BrowserTitle.DIALOG_TOP_RIGHT.getWidth(),
                        0,
                        Images.BrowserTitle.DIALOG_TOP_RIGHT.getWidth(),
                        Images.BrowserTitle.DIALOG_TOP_RIGHT.getHeight(), this);
            }
            
        }
        finally { g2.dispose(); }    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setLayout(new java.awt.GridBagLayout());

        setMaximumSize(new java.awt.Dimension(2147483647, 25));
        setMinimumSize(new java.awt.Dimension(57, 25));
        setPreferredSize(new java.awt.Dimension(57, 25));
        titleJLabel.setFont(Fonts.DialogTitle);
        titleJLabel.setText("!Dialog Title!");
        titleJLabel.setMaximumSize(new java.awt.Dimension(60, 16));
        titleJLabel.setMinimumSize(new java.awt.Dimension(60, 16));
        titleJLabel.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 9, 4, 0);
        add(titleJLabel, gridBagConstraints);

        closeJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_Close.png")));
        closeJButton.setBorderPainted(false);
        closeJButton.setContentAreaFilled(false);
        closeJButton.setFocusPainted(false);
        closeJButton.setFocusable(false);
        closeJButton.setMaximumSize(new java.awt.Dimension(14, 14));
        closeJButton.setMinimumSize(new java.awt.Dimension(14, 14));
        closeJButton.setPreferredSize(new java.awt.Dimension(14, 14));
        closeJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeJButtonMouseExited(evt);
            }
        });
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 6);
        add(closeJButton, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeJButtonMouseExited
        setCloseButtonIcon();
    }//GEN-LAST:event_closeJButtonMouseExited

    private void closeJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeJButtonMouseEntered
        if (closeButtonEnabled) {
            ((javax.swing.JButton) evt.getSource()).setIcon(CLOSE_ROLLOVER_ICON);
        }
    }//GEN-LAST:event_closeJButtonMouseEntered

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        if (closeButtonEnabled) {
            SwingUtilities.getWindowAncestor(WindowTitle.this).dispose();
        }
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * Set the appropriate close button icon.
     */
    private void setCloseButtonIcon() {
        if (closeButtonEnabled) {
            closeJButton.setIcon(CLOSE_ICON);
        } else {
            closeJButton.setIcon(CLOSE_DISABLED_ICON);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton closeJButton = new javax.swing.JButton();
    private final javax.swing.JLabel titleJLabel = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    /** The border types. */
    public enum BorderType { DEFAULT, WINDOW_BORDER2 }
}
