/*
 * WindowTitle.java
 *
 * Created on October 29, 2006, 4:11 PM
 */

package com.thinkparity.ophelia.browser.platform.application.window;

import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;

import javax.swing.Icon;
import javax.swing.SwingUtilities;

import com.thinkparity.codebase.swing.AbstractJPanel;

import com.thinkparity.ophelia.browser.Constants.Colors;
import com.thinkparity.ophelia.browser.Constants.Images;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.util.ImageIOUtil;

/**
 *
 * @author  Administrator
 */
public class WindowTitle extends AbstractJPanel {
    
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /** Close label icon. */
    private static final Icon CLOSE_ICON = ImageIOUtil.readIcon("BrowserTitle_Close.png");
    
    /** Close label rollover icon. */
    private static final Icon CLOSE_ROLLOVER_ICON = ImageIOUtil.readIcon("BrowserTitle_CloseRollover.png");

    /** Creates new form WindowTitle */
    public WindowTitle(final String title) {
        initComponents();
        titleJLabel.setText(title);
    }
    
    /** @see javax.swing.JComponent#paintComponent(java.awt.Graphics) */
    protected void paintComponent(final Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        try {
            // vertical gradient
            final Paint gPaint =
                new GradientPaint(0, 0, Colors.Browser.Window.TITLE_GRADIENT_TOP,
                                  0, getHeight(), Colors.Browser.Window.TITLE_GRADIENT_BOTTOM);
            g2.setPaint(gPaint);
            g2.fillRect(0, 0, getWidth(), getHeight());
            
            // These images put borders on rounded corners.
            g2.drawImage(Images.BrowserTitle.DIALOG_TOP_LEFT,
                    0,
                    0,
                    Images.BrowserTitle.DIALOG_TOP_LEFT.getWidth(),
                    Images.BrowserTitle.DIALOG_TOP_LEFT.getHeight(), this);
            g2.drawImage(Images.BrowserTitle.DIALOG_TOP_RIGHT,
                    getWidth() - Images.BrowserTitle.DIALOG_TOP_RIGHT.getWidth(),
                    0,
                    Images.BrowserTitle.DIALOG_TOP_RIGHT.getWidth(),
                    Images.BrowserTitle.DIALOG_TOP_RIGHT.getHeight(), this);
            
        }
        finally { g2.dispose(); }    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setLayout(new java.awt.GridBagLayout());

        setMaximumSize(new java.awt.Dimension(2147483647, 20));
        setMinimumSize(new java.awt.Dimension(57, 20));
        setPreferredSize(new java.awt.Dimension(57, 20));
        titleJLabel.setFont(Fonts.DialogTitle);
        titleJLabel.setText("!Dialog Title!");
        titleJLabel.setMaximumSize(new java.awt.Dimension(60, 16));
        titleJLabel.setMinimumSize(new java.awt.Dimension(60, 16));
        titleJLabel.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 9, 0, 0);
        add(titleJLabel, gridBagConstraints);

        closeJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_Close.png")));
        closeJButton.setBorderPainted(false);
        closeJButton.setContentAreaFilled(false);
        closeJButton.setFocusPainted(false);
        closeJButton.setFocusable(false);
        closeJButton.setMaximumSize(new java.awt.Dimension(14, 14));
        closeJButton.setMinimumSize(new java.awt.Dimension(14, 14));
        closeJButton.setPreferredSize(new java.awt.Dimension(14, 14));
        closeJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeJButtonMouseExited(evt);
            }
        });
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 6);
        add(closeJButton, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeJButtonMouseExited
        ((javax.swing.JButton) evt.getSource()).setIcon(CLOSE_ICON);
    }//GEN-LAST:event_closeJButtonMouseExited

    private void closeJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeJButtonMouseEntered
        ((javax.swing.JButton) evt.getSource()).setIcon(CLOSE_ROLLOVER_ICON);
    }//GEN-LAST:event_closeJButtonMouseEntered

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        SwingUtilities.getWindowAncestor(WindowTitle.this).dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton closeJButton = new javax.swing.JButton();
    private final javax.swing.JLabel titleJLabel = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

}
