select U.USER_ID,U.USERNAME,A.ARTIFACT_ID,A.ARTIFACT_UNIQUE_ID
from TPSD_BACKUP_USER_ARCHIVE BUA
inner join TPSD_ARTIFACT A on A.ARTIFACT_ID=BUA.ARTIFACT_ID
inner join TPSD_USER U on U.USER_ID=BUA.USER_ID;