select U.USERNAME,P.PRODUCT_NAME,PF.FEATURE_NAME
from TPSD_USER U
inner join TPSD_USER_FEATURE_REL UFR on UFR.USER_ID=U.USER_ID
inner join TPSD_PRODUCT_FEATURE PF on PF.FEATURE_ID=UFR.FEATURE_ID
inner join TPSD_PRODUCT P on P.PRODUCT_ID = PF.PRODUCT_ID
order by U.USER_ID asc,PF.FEATURE_NAME asc