select A.ARTIFACT_UNIQUE_ID "unique id",AV.ARTIFACT_VERSION_ID "version",AVS.SECRET_ALGORITHM "algorithm",AVS.SECRET_FORMAT "format",AVS.SECRET "secret"
from TPSD_ARTIFACT A
inner join TPSD_ARTIFACT_VERSION AV on AV.ARTIFACT_ID=A.ARTIFACT_ID
inner  join TPSD_ARTIFACT_VERSION_SECRET AVS oN AVS.ARTIFACT_ID=AV.ARTIFACT_ID and AVS.ARTIFACT_VERSION_ID=AV.ARTIFACT_VERSION_ID
