select A.ARTIFACT_NAME "name",CV.CONTAINER_VERSION_ID "version",CBU.JABBER_ID "created by",CVPT.PUBLISHED_ON "published on",U.JABBER_ID "published to",CVPT.RECEIVED_ON "received on"
from CONTAINER_VERSION_PUBLISHED_TO CVPT
inner join CONTAINER_VERSION CV on CV.CONTAINER_ID=CVPT.CONTAINER_ID and CV.CONTAINER_VERSION_ID=CVPT.CONTAINER_VERSION_ID
inner join ARTIFACT_VERSION AV on AV.ARTIFACT_ID=CV.CONTAINER_ID and AV.ARTIFACT_VERSION_ID=CV.CONTAINER_VERSION_ID
inner join ARTIFACT A on CV.CONTAINER_ID=A.ARTIFACT_ID
inner join PARITY_USER U on U.USER_ID=CVPT.USER_ID
inner join PARITY_USER CBU on CBU.USER_ID=AV.CREATED_BY
where A.ARTIFACT_UNIQUE_ID='f5fe04cc-35b2-436a-9097-d903aa8131ce'
order by CVPT.PUBLISHED_ON asc;