select A.ARTIFACT_UNIQUE_ID "id",A.CREATED_ON "created on",CBU.JABBER_ID "created by",TU.JABBER_ID "team member username"
from ARTIFACT_TEAM_REL ATR
inner join ARTIFACT A on A.ARTIFACT_ID=ATR.ARTIFACT_ID
inner join PARITY_USER TU on TU.USER_ID=ATR.USER_ID
inner join PARITY_USER CBU on CBU.USER_ID=A.CREATED_BY
where A.ARTIFACT_UNIQUE_ID = 'f53ad80a-3792-4894-8ffa-bc91c15365d3';