/*
 * Created on June 25, 2006, 12:24 PM
 * $Id$
 */

package com.thinkparity.migrator.application.migrator.avatar;

import com.thinkparity.codebase.assertion.Assert;

import com.thinkparity.migrator.application.migrator.Application;

/**
 *
 * @author raymond@thinkparity.com
 * @version $Revision$
 */
public class ReleaseSummary extends Avatar {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** The release table model. */
    private final ReleaseSummaryTableModel tableModel;

    /** Creates new form ReleaseSummary */
    public ReleaseSummary(final Application application) {
        super(application, "ReleaseSummary");
        this.tableModel = new ReleaseSummaryTableModel(this);
        initComponents();
    }

    /**
     * Obtain the release summary avatar id.
     *
     * @return The avatar id.
     */
    public AvatarId getId() { return AvatarId.RELEASE_SUMMARY; }

    /**
     * @see com.thinkparity.migrator.application.migrator.avatar.Avatar#setContentProvider(com.thinkparity.migrator.application.migrator.avatar.ContentProvider)
     * 
     */
    public void setContentProvider(final ContentProvider contentProvider) {
        Assert.assertNotNull("", contentProvider);
        Assert.assertOfType("", ContentProviderFlat.class, contentProvider);
        tableModel.setContentProvider((ContentProviderFlat) contentProvider);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JScrollPane releaseJScrollPane;

        releaseJScrollPane = new javax.swing.JScrollPane();
        releaseJTable = new javax.swing.JTable();

        releaseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        releaseJTable.setModel(tableModel.getTableModel());
        releaseJScrollPane.setViewportView(releaseJTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(releaseJScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 469, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(releaseJScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable releaseJTable;
    // End of variables declaration//GEN-END:variables

}
