/*
 * EMailUpdatedNotifyPage.java
 *
 * Created on October 12, 2007, 9:44 PM
 */

package com.thinkparity.ophelia.browser.application.system.dialog;

import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Colours;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.application.browser.component.ButtonFactory;
import com.thinkparity.ophelia.browser.application.system.SystemApplication;
import com.thinkparity.ophelia.browser.application.system.dialog.Notification.NotificationType;

/**
 *
 * @author robert@thinkparity.com
 */
public class EMailUpdatedNotifyPage extends DefaultNotifyPage {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JLabel offlineJLabel = new javax.swing.JLabel();
    private final javax.swing.JButton verifyEMailJButton = ButtonFactory.create();
    // End of variables declaration//GEN-END:variables

    /**
     * Create a new EMailUpdatedNotifyPage.
     * 
     * @param systemApplication
     *            The <code>SystemApplication</code>.
     */
    public EMailUpdatedNotifyPage(final SystemApplication systemApplication) {
        super(systemApplication);
        initComponents();
    }

    /**
     * @see com.thinkparity.ophelia.browser.application.system.dialog.NotifyPage#getType()
     */
    public NotificationType getType() {
        return NotificationType.EMAIL_UPDATED;
    }

    /**
     * @see com.thinkparity.ophelia.browser.application.system.dialog.NotifyPage#reload(com.thinkparity.ophelia.browser.application.system.dialog.Notification)
     */
    public void reload(final Notification notification) {
        super.reload(notification);
        reloadButton();
        reloadOfflineMessage();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        final javax.swing.JLabel messageJLabel = new javax.swing.JLabel();

        setOpaque(false);
        messageJLabel.setFont(Fonts.DialogFont);
        messageJLabel.setText(java.util.ResourceBundle.getBundle("localization/Browser_Messages").getString("SystemApplication.NotifyPage.EMailUpdated.Message"));
        messageJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        offlineJLabel.setFont(Fonts.DialogFont);
        offlineJLabel.setForeground(Colours.DIALOG_ERROR_TEXT_FG);
        offlineJLabel.setText("!Offline Message!");

        verifyEMailJButton.setFont(Fonts.DialogButtonFont);
        verifyEMailJButton.setText(java.util.ResourceBundle.getBundle("localization/Browser_Messages").getString("SystemApplication.NotifyPage.EMailUpdated.VerifyEMail"));
        verifyEMailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyEMailJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(offlineJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verifyEMailJButton))
                    .addComponent(messageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(verifyEMailJButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(offlineJLabel)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Reload the button.
     */
    private void reloadButton() {
        verifyEMailJButton.setEnabled(isOnline());
    }

    /**
     * Reload the offline message.
     */
    private void reloadOfflineMessage() {
        offlineJLabel.setText(isOnline() ? " " : systemApplication.getString("Notification.ErrorOffline"));
    }

    private void verifyEMailJButtonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyEMailJButtonActionPerformed
        closeNotification();
        notification.invokeAction();
    }//GEN-LAST:event_verifyEMailJButtonActionPerformed
}
