/*
 * Created on June 10, 2006, 12:00 PM
 */
package com.thinkparity.browser.platform.firstrun;

import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;

import com.thinkparity.codebase.assertion.Assert;

import com.thinkparity.browser.application.browser.BrowserConstants;
import com.thinkparity.browser.application.browser.component.ButtonFactory;
import com.thinkparity.browser.application.browser.component.LabelFactory;
import com.thinkparity.browser.application.browser.component.TextFactory;
import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;
import com.thinkparity.browser.platform.util.SwingUtil;

import com.thinkparity.model.parity.model.profile.Profile;
import com.thinkparity.model.xmpp.user.User;

/**
 * @author raymond@thinkparity.com
 * @version 1.1.2.6
 */
public class UserProfileAvatar extends Avatar {

    /**
     * Obtain a logging api id.
     * 
     * @param api
     *            The api.
     * @return A logging api id.
     */
    private static StringBuffer getApiId(final String api) {
        return getAvatarId(AvatarId.DIALOG_PROFILE_UPDATE).append(" ").append(api);
    }

    private String name;

    private String organization;

    private String title;

    /** Creates new form UserProfileAvatar */
    UserProfileAvatar(final FirstRunHelper firstRun) {
        super("UserProfileAvatar", BrowserConstants.DIALOGUE_BACKGROUND);
        initComponents();
        bindEnterKey("Finish", new AbstractAction() {
            private static final long serialVersionUID = 1;
            public void actionPerformed(final ActionEvent e) {
                finishJButtonActionPerformed(e);
            }
        });
        bindEscapeKey("Cancel", new AbstractAction() {
            private static final long serialVersionUID = 1;
            public void actionPerformed(final ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });
    }

    /** @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getId() */
    public AvatarId getId() { return AvatarId.DIALOG_PROFILE_UPDATE; }

    /** @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getState() */
    public State getState() {
        throw Assert.createNotYetImplemented("UserProfileAvatar#getState");
    }

    /** @see com.thinkparity.browser.platform.application.display.avatar.Avatar#reload() */
    public void reload() {
        reloadName();
        reloadOrganization();
        reloadTitle();
    }

    /** @see com.thinkparity.browser.platform.application.display.avatar.Avatar#setInput(java.lang.Object) */
    public void setInput(final Object input) {
        Assert.assertNotNull(getApiId("[SET INPUT]"), input);
        Assert.assertOfType(getApiId("[SET INPUT]"), Profile.class, input);
        this.input = input;
    }

    /** @see com.thinkparity.browser.platform.application.display.avatar.Avatar#setState(com.thinkparity.browser.platform.util.State) */
    public void setState(final State state) {
        throw Assert.createNotYetImplemented("UserProfileAvatar#setState");
    }

    String getFullName() { return name; }

    String getOrganization() { return organization; }

    String getTitle() { return title; }

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_cancelJButtonActionPerformed
        name = organization = title = null;
        disposeWindow();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private String extractName() {
        return SwingUtil.extract(nameJTextField);
    }

    private String extractOrganization() {
        return SwingUtil.extract(organizationJTextField);
    }

    private String extractTitle() {
        return SwingUtil.extract(titleJTextField);
    }

    private void finishJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_finishJButtonActionPerformed
        if(isInputValid()) {
            name = extractName();
            organization = extractOrganization();
            title = extractTitle();
            disposeWindow();
        }
    }//GEN-LAST:event_finishJButtonActionPerformed

    private String getInputName() {
        return ((User) input).getName();
    }

    private String getInputOrganization() {
        return ((User) input).getOrganization();
    }

    private String getInputTitle() {
        return ((User) input).getTitle();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton cancelJButton;
        javax.swing.JLabel eaJLabel;
        javax.swing.JButton finishJButton;
        javax.swing.JLabel nameJLabel;
        javax.swing.JLabel organizationJLabel;
        javax.swing.JLabel titleJLabel;
        javax.swing.JPanel userInfoJPanel;

        userInfoJPanel = new javax.swing.JPanel();
        nameJLabel = LabelFactory.create();
        organizationJLabel = LabelFactory.create();
        titleJLabel = LabelFactory.create();
        eaJLabel = new javax.swing.JLabel();
        nameJTextField = TextFactory.create();
        organizationJTextField = TextFactory.create();
        titleJTextField = TextFactory.create();
        finishJButton = ButtonFactory.create(getString("SaveButton"));
        cancelJButton = ButtonFactory.create(getString("CancelButton"));

        userInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.UserInfoTitle")));
        userInfoJPanel.setOpaque(false);
        nameJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.NameLabel"));

        organizationJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.OrganizationLabel"));

        titleJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.TitleLabel"));

        eaJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.EmbeddedAssistance"));

        finishJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.SaveButton"));
        finishJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                finishJButtonActionPerformed(e);
            }
        });

        cancelJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("UserProfileAvatar.CancelButton"));
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout userInfoJPanelLayout = new org.jdesktop.layout.GroupLayout(userInfoJPanel);
        userInfoJPanel.setLayout(userInfoJPanelLayout);
        userInfoJPanelLayout.setHorizontalGroup(
            userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(userInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, nameJLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, organizationJLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, titleJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(organizationJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
            .add(userInfoJPanelLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(eaJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, userInfoJPanelLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .add(cancelJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(finishJButton)
                .addContainerGap())
        );
        userInfoJPanelLayout.setVerticalGroup(
            userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(userInfoJPanelLayout.createSequentialGroup()
                .add(eaJLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameJLabel)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(organizationJLabel)
                    .add(organizationJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleJLabel)
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(userInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(finishJButton)
                    .add(cancelJButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(userInfoJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(userInfoJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reloadName() {
        nameJTextField.setText("");
        if(null != input) { nameJTextField.setText(getInputName()); }
    }

    private void reloadOrganization() {
        organizationJTextField.setText("");
        if(null != input) {
            organizationJTextField.setText(getInputOrganization());
        }
    }

    private void reloadTitle() {
        titleJTextField.setText("");
        if (null != input) {
            titleJTextField.setText(getInputTitle());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField organizationJTextField;
    private javax.swing.JTextField titleJTextField;
    // End of variables declaration//GEN-END:variables

}
