/*
 * Jan 20, 2006
 */
package com.thinkparity.browser.application.browser.display.avatar;

/**
 * @author raykroeker@gmail.com
 * @version 1.1
 */
public enum AvatarId {
    DIALOG_CONFIRM, DIALOG_CONTACT_CREATE_OUTGOING_INVITATION, DIALOG_CONTACT_READ, DIALOG_CONTAINER_CREATE, DIALOG_CONTAINER_UPDATE_TEAM, DIALOG_ERROR, DIALOG_PROFILE_UPDATE, DIALOG_RENAME, MAIN_CONTENT, MAIN_STATUS, MAIN_TITLE, DIALOG_PLATFORM_LOGIN, TAB_CONTACT, TAB_CONTAINER
}
