/*
 * Created on July 31, 2006, 5:27 PM
 */
package com.thinkparity.browser.application.browser.display.avatar;

import com.thinkparity.browser.Constants.Icons;
import com.thinkparity.browser.javax.swing.AbstractJPanel;
import com.thinkparity.browser.platform.util.State;

import com.thinkparity.codebase.assertion.Assert;

/**
 *
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class BrowserTitleTabs extends AbstractJPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** The browser title avatar. */
    private BrowserTitle browserTitle;

    /** Creates new form BrowserTitleTabs */
    public BrowserTitleTabs() {
        super("BrowserTitleTabs");
        initComponents();
    }

    /**
     * Set the browser title avatar.
     * 
     * @param avatar
     *            The title avatar.
     */
    void setBrowserTitle(final BrowserTitle browserTitle) {
        this.browserTitle = browserTitle;
    }
    
    /**
     * Update the tab icon. This is called when the browser
     * is reopened.
     * 
     * @param tab
     *          The selected tab.
     */
    void updateTabIcon(final BrowserTitleTab tab) {
        switch(tab) {
        case CONTACTS:
            contactsJLabel.setIcon(Icons.BrowserTitle.CONTACTS_TAB_SELECTED);
            containersJLabel.setIcon(Icons.BrowserTitle.CONTAINERS_TAB);
            break;
        case CONTAINERS:
            contactsJLabel.setIcon(Icons.BrowserTitle.CONTACTS_TAB);
            containersJLabel.setIcon(Icons.BrowserTitle.CONTAINERS_TAB_SELECTED);
            break;
        default:
            Assert.assertUnreachable("[BROWSER TITLETABS] [SELECT] [UNKNOWN TAB] [" + tab + "]");
        }
    }
    
    private void contactsJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_contactsJLabelMouseClicked
        contactsJLabel.setIcon(Icons.BrowserTitle.CONTACTS_TAB_SELECTED);
        containersJLabel.setIcon(Icons.BrowserTitle.CONTAINERS_TAB);
        browserTitle.select(BrowserTitleTab.CONTACTS);
    }//GEN-LAST:event_contactsJLabelMouseClicked

    private void containersJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_containersJLabelMouseClicked
        contactsJLabel.setIcon(Icons.BrowserTitle.CONTACTS_TAB);
        containersJLabel.setIcon(Icons.BrowserTitle.CONTAINERS_TAB_SELECTED);
        browserTitle.select(BrowserTitleTab.CONTAINERS);
    }//GEN-LAST:event_containersJLabelMouseClicked
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        containersJLabel = new javax.swing.JLabel();
        contactsJLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        containersJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ContainersTabSelected.png")));
        containersJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                containersJLabelMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(containersJLabel, gridBagConstraints);

        contactsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ContactsTab.png")));
        contactsJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsJLabelMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(contactsJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactsJLabel;
    private javax.swing.JLabel containersJLabel;
    // End of variables declaration//GEN-END:variables
}
