/*
 * BrowserTitleMenu.java
 *
 * Created on July 30, 2006, 3:33 PM
 */

package com.thinkparity.browser.application.browser.display.avatar;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;

import com.thinkparity.browser.Constants.Colors;
import com.thinkparity.browser.javax.swing.AbstractJPanel;

/**
 *
 * @author raymond@thinkparity.com
 */
public class BrowserTitleMenu extends AbstractJPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /** The avatar the button title menu reside upon. */
    private BrowserTitle browserTitle;

    /** Creates new form BrowserTitleMenu */
    public BrowserTitleMenu() {
        super("BrowserTitleMenu.MenuPanel");
        initComponents();
    }

    /**
     * Set the browser title.
     * 
     * @param browserTitle
     *            The browser title.
     */
    void setBrowserTitle(final BrowserTitle browserTitle) {
        this.browserTitle = browserTitle;
    }

    /**
     * @see javax.swing.JComponent#paintComponent(java.awt.Graphics)
     */
    @Override
    protected void paintComponent(final Graphics g) {
        super.paintComponent(g);
        final Graphics g2 = g.create();
        try {
            if(signUpJLabel.isVisible()) {
                g.setColor(Colors.BrowserTitle.SIGN_UP_BACKGROUND);
                final Point location = signUpJLabel.getLocation();
                final Dimension size = signUpJLabel.getSize();
                g.fillRoundRect(
                        location.x - 4, location.y - 2,
                        size.width + 8, size.height + 4,
                        4, 4);
            }
        }
        finally { g2.dispose(); }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel helpJLabel;
        javax.swing.JLabel newJLabel;
        javax.swing.JLabel profileJLabel;
        javax.swing.JLabel spacerJLabel;

        newJLabel = new javax.swing.JLabel();
        profileJLabel = new javax.swing.JLabel();
        helpJLabel = new javax.swing.JLabel();
        signUpJLabel = new javax.swing.JLabel();
        spacerJLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        newJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.New"));
        newJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newJLabelMouseExited(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        add(newJLabel, gridBagConstraints);

        profileJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.Profile"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(profileJLabel, gridBagConstraints);

        helpJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.Help"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(helpJLabel, gridBagConstraints);

        signUpJLabel.setText(java.util.ResourceBundle.getBundle("localization/BrowserLocalization").getString("com.thinkparity.browser.application.browser.display.avatar.BrowserTitle.SignUp"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(signUpJLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(spacerJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void newJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseEntered
// TODO add your handling code here:
    }//GEN-LAST:event_newJLabelMouseEntered

    private void newJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseExited
// TODO add your handling code here:
    }//GEN-LAST:event_newJLabelMouseExited

    private void newJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newJLabelMouseClicked
        browserTitle.getController().runAddContact();
        newJLabelMouseExited(evt);
    }//GEN-LAST:event_newJLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel signUpJLabel;
    // End of variables declaration//GEN-END:variables
}
