/*
 * BrowserTitleSearch.java
 *
 * Created on July 30, 2006, 3:30 PM
 */
package com.thinkparity.browser.application.browser.display.avatar;

import com.thinkparity.browser.Constants.Colors;
import com.thinkparity.browser.javax.swing.border.TopBottomBorder;

/**
 *
 * @author raymond@thinkparity.com
 */
public class BrowserTitleSearch extends javax.swing.JPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** The browser title container. */
    private BrowserTitle browserTitle;

    /** Creates new form BrowserTitleSearch */
    public BrowserTitleSearch() {
        initComponents();
    }

    /**
     * Set browserTitle.
     * 
     * @param browserTitle
     *            The BrowserTitle.
     */
    public void setBrowserTitle(final BrowserTitle browserTitle) {
        this.browserTitle = browserTitle;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel leftJLabel;
        javax.swing.JLabel rightJLabel;

        rightJLabel = new javax.swing.JLabel();
        searchJTextField = new javax.swing.JTextField();
        searchJTextField.setBorder(new TopBottomBorder(Colors.BrowserTitle.SEARCH_OUTLINE));
        searchJTextField.setBackground(Colors.BrowserTitle.SEARCH_BACKGROUND);
        leftJLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        rightJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_SearchRight.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 7);
        add(rightJLabel, gridBagConstraints);

        searchJTextField.setPreferredSize(new java.awt.Dimension(11, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        add(searchJTextField, gridBagConstraints);

        leftJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_SearchLeft.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        add(leftJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField searchJTextField;
    // End of variables declaration//GEN-END:variables
}
