/*
 * Created on July 31, 2006, 5:27 PM
 */
package com.thinkparity.browser.application.browser.display.avatar;

import com.thinkparity.browser.Constants.Icons;

/**
 *
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class BrowserTitleTabs extends javax.swing.JPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** The browser title avatar. */
    private BrowserTitle browserTitle;

    /** Creates new form BrowserTitleTabs */
    public BrowserTitleTabs() {
        initComponents();
    }

    /**
     * Set the browser title avatar.
     * 
     * @param avatar
     *            The title avatar.
     */
    void setBrowserTitle(final BrowserTitle browserTitle) {
        this.browserTitle = browserTitle;
    }
    private void contactsJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_contactsJLabelMouseClicked
        contactsJLabel.setIcon(Icons.BrowserTitle.CONTACTS_TAB_SELECTED);
        containersJLabel.setIcon(Icons.BrowserTitle.CONTAINERS_TAB);
        browserTitle.select(BrowserTitleTab.CONTACTS);
    }//GEN-LAST:event_contactsJLabelMouseClicked

    private void containersJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_containersJLabelMouseClicked
        contactsJLabel.setIcon(Icons.BrowserTitle.CONTACTS_TAB);
        containersJLabel.setIcon(Icons.BrowserTitle.CONTAINERS_TAB_SELECTED);
        browserTitle.select(BrowserTitleTab.CONTAINERS);
    }//GEN-LAST:event_containersJLabelMouseClicked
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        containersJLabel = new javax.swing.JLabel();
        contactsJLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        containersJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ContainersTab.png")));
        containersJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                containersJLabelMouseClicked(e);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(containersJLabel, gridBagConstraints);

        contactsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ContactsTab.png")));
        contactsJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                contactsJLabelMouseClicked(e);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(contactsJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactsJLabel;
    private javax.swing.JLabel containersJLabel;
    // End of variables declaration//GEN-END:variables
}
