/*
 * BrowserStatus.java
 *
 * Created on July 29, 2006, 8:58 AM
 */

package com.thinkparity.browser.application.browser.display.avatar;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;

import javax.swing.JLabel;

import com.thinkparity.browser.Constants.Colors;
import com.thinkparity.browser.codebase.swing.GradientPainter;
import com.thinkparity.browser.javax.swing.border.TopBorder;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;

/**
 * <b>Title:</b>thinkParity Browser Status<br>
 * <b>Description:</b>Displays the status bar at the bottom of the browser
 * window.
 * 
 * @author raymond@thinkparity.com
 */
public class BrowserStatus extends Avatar {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** Creates new form BrowserStatus */
    BrowserStatus() {
        super("BrowserStatus");
        initComponents();
    }

    public void clear(final BrowserStatusArea area) {}

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getId()
     */
    @Override
    public AvatarId getId() { return AvatarId.STATUS; }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getState()
     */
    @Override
    public State getState() { return null; }

    public void setMessage(final BrowserStatusArea area, final String messageKey) {}

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#setState(com.thinkparity.browser.platform.util.State)
     */
    @Override
    public void setState(final State state) {}

    /**
     * @see javax.swing.JComponent#paintComponent(java.awt.Graphics)
     */
    @Override
    protected void paintComponent(final Graphics g) {
        super.paintComponent(g);
        final Graphics g2 = g.create();
        try {
            GradientPainter.paintVertical(g2, getSize(),
                    Colors.BrowserStatus.BG_GRAD_START,
                    Colors.BrowserStatus.BG_GRAD_FINISH);
        }
        finally { g2.dispose(); }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JLabel offlineJLabel;
        javax.swing.JLabel resizeJLabel;
        javax.swing.JLabel statusMessageJLabel;

        statusMessageJLabel = new javax.swing.JLabel();
        resizeJLabel = new javax.swing.JLabel();
        offlineJLabel = new javax.swing.JLabel();

        setBorder(new TopBorder(Colors.BrowserStatus.TOP_BORDER));
        statusMessageJLabel.setText("Venture Capital Agreements:  Updated 10:30 AM");

        resizeJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserStatus_Resize.png")));
        resizeJLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent e) {
                resizeJLabelMouseDragged(e);
            }
        });
        resizeJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                resizeJLabelMouseEntered(e);
            }
            public void mousePressed(java.awt.event.MouseEvent e) {
                resizeJLabelMousePressed(e);
            }
        });

        offlineJLabel.setText("Offline");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(statusMessageJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 153, Short.MAX_VALUE)
                .add(offlineJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(resizeJLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(offlineJLabel)
                    .add(statusMessageJLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .add(resizeJLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int resizeOffsetX;

    private int resizeOffsetY;

    private void resizeJLabelMousePressed(java.awt.event.MouseEvent e) {//GEN-FIRST:event_resizeJLabelMousePressed
        resizeOffsetX = e.getPoint().x;
        resizeOffsetY = e.getPoint().y;
    }//GEN-LAST:event_resizeJLabelMousePressed

    private void resizeJLabelMouseDragged(java.awt.event.MouseEvent e) {//GEN-FIRST:event_resizeJLabelMouseDragged
        getController().resizeBrowserWindow(
                new Dimension(
                        e.getPoint().x - resizeOffsetX,
                        e.getPoint().y - resizeOffsetY));
    }//GEN-LAST:event_resizeJLabelMouseDragged

    private void resizeJLabelMouseEntered(java.awt.event.MouseEvent e) {//GEN-FIRST:event_resizeJLabelMouseEntered
        ((JLabel) e.getSource()).setCursor(new Cursor(Cursor.NW_RESIZE_CURSOR));
    }//GEN-LAST:event_resizeJLabelMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
