/*
 * SessionInvitePartner.java
 *
 * Created on March 25, 2006, 12:04 PM
 */

package com.thinkparity.browser.application.browser.display.avatar;

import java.awt.Color;

import javax.swing.SwingUtilities;

import com.thinkparity.browser.application.browser.component.ButtonFactory;
import com.thinkparity.browser.application.browser.component.LabelFactory;
import com.thinkparity.browser.application.browser.component.TextFactory;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;

/**
 *
 * @author  raymond
 */
public class SessionInvitePartner extends Avatar {

	/**
	 * @see java.io.Serializable
	 * 
	 */
	private static final long serialVersionUID = 1;

    /** Creates new form SessionInvitePartner */
    public SessionInvitePartner() {
	super("InvitePartner", Color.WHITE);
	initComponents();
    }
    
    /**
     * Set the avatar state.
     *
     *
     * @param state
     *            The avatar's state information.
     */
    public void setState(final State state) {}
    
    /**
     * Obtain the avatar's state information.
     *
     *
     * @return The avatar's state information.
     */
    public State getState() { return null; }
    
    /**
     * Obtain the avatar id.
     *
     *
     * @return The avatar id.
     */
    public AvatarId getId() { return AvatarId.SESSION_INVITE_PARTNER; }

    private void disposeWindow() {
    	SwingUtilities.getWindowAncestor(this).dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton closeJButton;
        javax.swing.JLabel eaJLabel;
        javax.swing.JLabel emailJLabel;
        javax.swing.JButton inviteJButton;
        javax.swing.JButton manageJButton;

        eaJLabel = LabelFactory.create(getString("EmbeddedAssistance"));
        emailJLabel = LabelFactory.create(getString("EmailLabel"));
        emailJTextField = TextFactory.create();
        inviteJButton = ButtonFactory.create(getString("InviteButton"));
        closeJButton = ButtonFactory.create(getString("CloseButton"));
        manageJButton = ButtonFactory.create(getString("ManageButton"));

        inviteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                inviteJButtonActionPerformed(e);
            }
        });

        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                closeJButtonActionPerformed(e);
            }
        });

        manageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                manageJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(eaJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(emailJLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(emailJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, inviteJButton)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(manageJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(closeJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(eaJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailJLabel)
                    .add(emailJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inviteJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(closeJButton)
                    .add(manageJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_manageJButtonActionPerformed
    	disposeWindow();
    	getController().displaySessionManageContacts();
    }//GEN-LAST:event_manageJButtonActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_closeJButtonActionPerformed
    	disposeWindow();
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void inviteJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_inviteJButtonActionPerformed
    	if(isInputValid()) {
    		
    	}
    }//GEN-LAST:event_inviteJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailJTextField;
    // End of variables declaration//GEN-END:variables
    
}
