/*
 * Created On: Sept 1, 2006, 8:10 AM
 */
package com.thinkparity.browser.application.browser.display.avatar.tab.archive;

import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.application.browser.display.avatar.Resizer;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;

/**
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class ArchiveAvatar extends Avatar {
    
    /** Create ArchiveAvatar. */
    public ArchiveAvatar() {
        super(AvatarId.TAB_ARCHIVE);
        setResizeEdges(Resizer.FormLocation.MIDDLE);
        initComponents();
    }

    /**
     * Set the avatar state.
     * 
     * 
     * @param state
     *            The avatar's state information.
     */
    public void setState(final State state) {}

    /**
     * Obtain the avatar's state information.
     * 
     * 
     * @return The avatar's state information.
     */
    public State getState() {
        return null;
    }

    /**
     * Obtain the avatar id.
     * 
     * 
     * @return The avatar id.
     */
    public AvatarId getId() {
        return AvatarId.TAB_ARCHIVE;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        archiveJScrollPane = new javax.swing.JScrollPane();
        archiveJList = new javax.swing.JList();

        archiveJScrollPane.setViewportView(archiveJList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(archiveJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(archiveJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList archiveJList;
    private javax.swing.JScrollPane archiveJScrollPane;
    // End of variables declaration//GEN-END:variables
}
