/*
 * VersionContentCellRenderer.java
 *
 * Created on October 7, 2006, 1:34 PM
 */

package com.thinkparity.ophelia.browser.application.browser.display.renderer.tab.container;

import java.awt.Component;

import javax.swing.JList;
import javax.swing.ListCellRenderer;

import com.thinkparity.codebase.swing.AbstractJPanel;
import com.thinkparity.ophelia.browser.Constants.Colors.Swing;
import com.thinkparity.ophelia.browser.application.browser.display.renderer.tab.container.ContainerVersionsPanel.VersionContentCell;

/**
 *
 * @author  raymond
 */
public class VersionContentCellRenderer extends AbstractJPanel implements
        ListCellRenderer {
    
    /** Creates new form VersionContentCellRenderer */
    public VersionContentCellRenderer() {
        initComponents();
    }

    /**
     * @see javax.swing.ListCellRenderer#getListCellRendererComponent(javax.swing.JList,
     *      java.lang.Object, int, boolean, boolean)
     */
    public Component getListCellRendererComponent(final JList list,
            final Object value, final int index, final boolean isSelected,
            final boolean cellHasFocus) {
        final VersionContentCell cell = (VersionContentCell) value;
        textJLabel.setText(cell.getText());

        if (isSelected) {
            textJLabel.setForeground(Swing.LIST_SELECTION_FG);
            setBackground(Swing.LIST_SELECTION_BG);
        } else {
            textJLabel.setForeground(Swing.LIST_FG);
            if (0 == index % 2) {
                setBackground(Swing.LIST_EVEN_BG);
            } else {
                setBackground(Swing.LIST_ODD_BG);
            }
        }

        return this;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textJLabel = new javax.swing.JLabel();

        textJLabel.setText("!VersionContent!");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textJLabel)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel textJLabel;
    // End of variables declaration//GEN-END:variables
    
}
