select CI.CONTACT_INVITATION_ID "id",UC.USERNAME "created by",
    CI.CREATED_ON "created on",U.USERNAME "user",E.EMAIL "e-mail",
    UEB.USERNAME "extended by"
from TPSD_CONTACT_INVITATION_INCOMING_EMAIL CIIE
    inner join TPSD_CONTACT_INVITATION CI on CI.CONTACT_INVITATION_ID=CIIE.CONTACT_INVITATION_ID
    inner join TPSD_USER UC on UC.USER_ID=CI.CREATED_BY
    inner join TPSD_USER U on U.USER_ID=CIIE.USER_ID
    inner join TPSD_EMAIL E on E.EMAIL_ID=CIIE.EMAIL_ID
    inner join TPSD_USER UEB on UEB.USER_ID=CIIE.EXTENDED_BY_USER_ID
order by CIIE.USER_ID asc,CI.CREATED_ON asc