select PR.RELEASE_NAME,PRRR.RESOURCE_ID,PRRR.RESOURCE_PATH
from TPSD_PRODUCT_RELEASE_RESOURCE_REL PRRR
inner join TPSD_PRODUCT_RELEASE PR on PR.RELEASE_ID=PRRR.RELEASE_ID
where PRRR.RESOURCE_PATH='/lib/commons-codec.jar';