select PR.RELEASE_NAME,PRR.RESOURCE_CHECKSUM,PRR.RESOURCE_CHECKSUM_ALGORITHM,PRR.RESOURCE_ID,PRR.RESOURCE_SIZE,PRRR.RESOURCE_PATH
from TPSD_PRODUCT_RELEASE_RESOURCE PRR
    inner join TPSD_PRODUCT_RELEASE_RESOURCE_REL PRRR on PRRR.RESOURCE_ID=PRR.RESOURCE_ID
    inner join TPSD_PRODUCT_RELEASE PR on PR.RELEASE_ID=PRRR.RELEASE_ID
where RESOURCE_PATH = '/core/browser.jar';