select A.ARTIFACT_UNIQUE_ID "id",A.ARTIFACT_NAME "name",CBU.NAME "created by",
    AV.CREATED_ON "created on",DV.DOCUMENT_VERSION_ID "version",
    DV.CONTENT_SIZE "size"
from DOCUMENT_VERSION DV
inner join ARTIFACT A on A.ARTIFACT_ID=DV.DOCUMENT_ID
inner join ARTIFACT_VERSION AV on AV.ARTIFACT_ID=DV.DOCUMENT_ID and AV.ARTIFACT_VERSION_ID=DV.DOCUMENT_VERSION_ID
inner join PARITY_USER CBU on CBU.USER_ID=AV.CREATED_BY
order by AV.CREATED_ON desc
