/*
 * ProfileEMailCellRenderer.java
 *
 * Created on August 25, 2006, 8:35 AM
 */

package com.thinkparity.ophelia.browser.application.browser.display.renderer.dialog.profile;

import java.awt.Component;

import javax.swing.JList;
import javax.swing.ListCellRenderer;

import com.thinkparity.codebase.swing.AbstractJPanel;

import com.thinkparity.ophelia.browser.Constants.Colors.Browser.UpdateProfile;

/**
 *
 * @author raymond@thinkparity.com
 * 
 */
public class ProfileEMailCellRenderer extends AbstractJPanel implements
        ListCellRenderer {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /**
     * Creates new form ProfileEMailCellRenderer
     */
    public ProfileEMailCellRenderer() {
        super();
        initComponents();
    }

    /**
     * @see javax.swing.ListCellRenderer#getListCellRendererComponent(javax.swing.JList,
     *      java.lang.Object, int, boolean, boolean)
     * 
     */
    public Component getListCellRendererComponent(final JList list,
            final Object value, final int index, final boolean isSelected,
            final boolean cellHasFocus) {
        final ProfileEMailCell emailCell = (ProfileEMailCell) value;
        emailJLabel.setText(emailCell.getEmail().toString());
        statusJLabel.setText(emailCell.isVerified() ? "" : "!NOT VERIFIED!");

        if (isSelected) {
            setBackground(UpdateProfile.EMAIL_CELL_BG_SELECTED);
        } else {
            setBackground(UpdateProfile.EMAIL_CELL_BG);
        }

        return this;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        emailJLabel = new javax.swing.JLabel();
        statusJLabel = new javax.swing.JLabel();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(emailJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(statusJLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailJLabel)
                    .add(statusJLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel statusJLabel;
    // End of variables declaration//GEN-END:variables
    
}
