/*
 * UserInfoAvatar.java
 *
 * Created on December 6, 2006, 10:09 AM
 */

package com.thinkparity.ophelia.browser.application.browser.display.avatar.dialog.contact;

import com.thinkparity.codebase.jabber.JabberId;
import com.thinkparity.codebase.model.user.User;

import com.thinkparity.ophelia.browser.application.browser.BrowserConstants;
import com.thinkparity.ophelia.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.ophelia.browser.application.browser.display.provider.SingleContentProvider;
import com.thinkparity.ophelia.browser.platform.action.Data;
import com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.ophelia.browser.platform.util.State;

/**
 *
 * @author  Administrator
 */
public class UserInfoAvatar extends Avatar {
    
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** Creates new form UserInfoAvatar */
    public UserInfoAvatar() {
        super("UserInfoDialog", BrowserConstants.DIALOGUE_BACKGROUND);
        initComponents();
    }
    
    public AvatarId getId() {
        return AvatarId.DIALOG_CONTACT_READ;
    }
    
    public void setState(final State state) {
    }

    public State getState() {
        return null;
    }
    
    /**
     * Obtain the input user id.
     *
     * @return A user id.
     */
    private JabberId getInputUserId() {
        if (input!=null) {
            return (JabberId) ((Data) input).get(DataKey.USER_ID);
        }
        else {
            return null;
        }
    }
    
    /**
     * Obtain the user.
     *
     * @return The user.
     */
    private User getUser(JabberId userId) {
        return (User) ((SingleContentProvider) contentProvider).getElement((Object)userId);
    }
    
    public void reload() {
        // Clear controls for contact name, company, and email
        nameJTextField.setText("");
        companyJTextField.setText("");
        titleJTextField.setText("");
        
        JabberId id = getInputUserId();
        if (id != null) {
            final User user = getUser(id);
            if (user != null) {
                nameJTextField.setText(user.getName());
                companyJTextField.setText(user.getOrganization());
                titleJTextField.setText(user.getTitle()); 
            }
        }
        
        closeJButton.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        closeJButton = new javax.swing.JButton();
        nameJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        titleJLabel = new javax.swing.JLabel();
        titleJTextField = new javax.swing.JTextField();
        companyJLabel = new javax.swing.JLabel();
        companyJTextField = new javax.swing.JTextField();

        closeJButton.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("UserInfoDialog.Close"));
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        nameJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("UserInfoDialog.Name"));

        nameJTextField.setEditable(false);

        titleJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("UserInfoDialog.TitleLabel"));

        titleJTextField.setEditable(false);

        companyJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("UserInfoDialog.Company"));

        companyJTextField.setEditable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, closeJButton)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(companyJLabel)
                        .add(14, 14, 14)
                        .add(companyJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(titleJLabel)
                        .add(14, 14, 14)
                        .add(titleJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(nameJLabel)
                        .add(14, 14, 14)
                        .add(nameJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {companyJLabel, nameJLabel, titleJLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(titleJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(companyJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(companyJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(closeJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_closeJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel companyJLabel;
    private javax.swing.JTextField companyJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JTextField titleJTextField;
    // End of variables declaration//GEN-END:variables

    public enum DataKey { USER_ID }
}
