/*
 * Created on August 24, 2006, 9:45 AM
 */
package com.thinkparity.browser.application.browser.display.avatar.dialog.profile;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;

import com.thinkparity.codebase.email.EMail;
import com.thinkparity.codebase.email.EMailBuilder;

import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.application.browser.display.provider.SingleContentProvider;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;
import com.thinkparity.browser.platform.util.SwingUtil;

import com.thinkparity.model.parity.model.profile.Profile;

/**
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class UpdateProfileAvatar extends Avatar {
    
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** The email address list model. */
    private final DefaultListModel emailsModel;

    /** Creates new form UpdateProfileAvatar */
    public UpdateProfileAvatar() {
        super("UpdateProfileAvatar");
        this.emailsModel = new DefaultListModel();
        initComponents();
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getId()
     * 
     */
    public AvatarId getId() {
        return AvatarId.DIALOG_PROFILE_UPDATE;
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getState()
     * 
     */
    public State getState() {
        return null;
    }

    /**
     * @see com.thinkparity.codebase.swing.AbstractJPanel#isInputValid()
     */
    @Override
    public Boolean isInputValid() {
        final String name = extractInputName();
        final String organization = extractInputOrganization();
        final String title = extractInputTitle();
        if (null != name && null != organization && null != title) {
            return Boolean.TRUE;
        } else {
            return Boolean.FALSE;
        }
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#reload()
     */
    @Override
    public void reload() {
        final Profile  profile = readProfile();
        reloadName(profile);
        reloadOrganization(profile);
        reloadTitle(profile);
        reloadEmails(profile);
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#setState(com.thinkparity.browser.platform.util.State)
     * 
     */
    public void setState(final State state) {}

    private void addJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_addJButtonActionPerformed
        final EMail email = extractInputEmail();
        if (null != email) {
            if (!emailsModel.contains(email)) {
                emailJTextField.setText("");
                emailsModel.addElement(email);
            }
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_cancelJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void emailJTextFieldActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_emailJTextFieldActionPerformed
        addJButtonActionPerformed(e);
    }//GEN-LAST:event_emailJTextFieldActionPerformed

    private EMail extractInputEmail() {
        return EMailBuilder.parse(SwingUtil.extract(emailJTextField));
    }

    private String extractInputName() {
        return SwingUtil.extract(nameJTextField);
    }

    private String extractInputOrganization() {
        return SwingUtil.extract(organizationJTextField);
    }

    private String extractInputTitle() {
        return SwingUtil.extract(titleJTextField);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton addJButton;
        javax.swing.JButton cancelJButton;
        javax.swing.JLabel eaJLabel;
        javax.swing.JLabel emailsJLabel;
        javax.swing.JScrollPane emailsJScrollPane;
        javax.swing.JPanel innerJPanel;
        javax.swing.JSeparator jSeparator1;
        javax.swing.JLabel nameJLabel;
        javax.swing.JLabel organizationJLabel;
        javax.swing.JButton removeJButton;
        javax.swing.JButton saveJButton;
        javax.swing.JLabel titleJLabel;

        innerJPanel = new javax.swing.JPanel();
        eaJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        organizationJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        organizationJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        titleJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        emailsJLabel = new javax.swing.JLabel();
        emailsJScrollPane = new javax.swing.JScrollPane();
        emailsJList = new javax.swing.JList();
        addJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        emailJTextField = new javax.swing.JTextField();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();

        setOpaque(false);
        innerJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.InnerPanelTitle")));
        innerJPanel.setOpaque(false);
        eaJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.EmbeddedAssistance"));

        nameJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.NameLabel"));

        organizationJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.OrganizationLabel"));

        titleJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.TitleLabel"));

        emailsJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.EmailsLabel"));

        emailsJList.setModel(emailsModel);
        emailsJScrollPane.setViewportView(emailsJList);

        addJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.AddEmailButton"));
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                addJButtonActionPerformed(e);
            }
        });

        removeJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.RemoveEmailButton"));
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                removeJButtonActionPerformed(e);
            }
        });

        emailJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                emailJTextFieldActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout innerJPanelLayout = new org.jdesktop.layout.GroupLayout(innerJPanel);
        innerJPanel.setLayout(innerJPanelLayout);
        innerJPanelLayout.setHorizontalGroup(
            innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(emailsJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .add(innerJPanelLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(eaJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap(91, Short.MAX_VALUE))
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameJLabel)
                    .add(organizationJLabel)
                    .add(titleJLabel))
                .add(13, 13, 13)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(innerJPanelLayout.createSequentialGroup()
                        .add(emailJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                        .add(removeJButton))
                    .add(emailsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .add(organizationJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addContainerGap())
        );
        innerJPanelLayout.setVerticalGroup(
            innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(eaJLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameJLabel)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(organizationJLabel)
                    .add(organizationJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleJLabel)
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailsJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailsJScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addJButton)
                    .add(removeJButton)
                    .add(emailJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.SaveButton"));
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                saveJButtonActionPerformed(e);
            }
        });

        cancelJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.CancelButton"));
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, innerJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(cancelJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(innerJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveJButton)
                    .add(cancelJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Read the profile from the content provider.
     * @return
     */
    private Profile readProfile() {
        return (Profile) ((SingleContentProvider) contentProvider).getElement(null);
    }

    private void reloadEmails(final Profile profile) {
        emailsModel.clear();
        for (final EMail email : profile.getEmails()) {
            emailsModel.addElement(email);
        }
    }

    private void reloadName(final Profile profile) {
        nameJTextField.setText("");
        final String name = profile.getName();
        if (null != name) {
            nameJTextField.setText(name);
        }
    }
    private void reloadOrganization(final Profile profile) {
        organizationJTextField.setText("");
        final String organization = profile.getOrganization();
        if (null != organization) {
            organizationJTextField.setText(organization);
        }
    }
    private void reloadTitle(final Profile profile) {
        titleJTextField.setText("");
        final String title = profile.getTitle();
        if (null != title) {
            titleJTextField.setText(title);
        }
    }

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_removeJButtonActionPerformed
        final Object[] values = emailsJList.getSelectedValues();
        for (final Object value : values) {
            emailsModel.removeElement(value);
        }
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_saveJButtonActionPerformed
        if (isInputValid()) {
            final List<String> emails = new ArrayList<String>(0);
            final String name = extractInputName();
            final String organization = extractInputOrganization();
            final String title = extractInputTitle();
            getController().runUpdateProfile(emails, name, organization, title);
            disposeWindow();
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JList emailsJList;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField organizationJTextField;
    private javax.swing.JTextField titleJTextField;
    // End of variables declaration//GEN-END:variables
}
