/*
 * Created on August 24, 2006, 9:45 AM
 */
package com.thinkparity.browser.application.browser.display.avatar.dialog.profile;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.AbstractAction;

import com.thinkparity.codebase.email.EMail;
import com.thinkparity.codebase.email.EMailBuilder;

import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.application.browser.display.provider.CompositeFlatSingleContentProvider;
import com.thinkparity.browser.application.browser.display.renderer.dialog.profile.ProfileEMailCell;
import com.thinkparity.browser.application.browser.display.renderer.dialog.profile.ProfileEMailCellRenderer;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;
import com.thinkparity.browser.platform.util.SwingUtil;

import com.thinkparity.model.parity.model.profile.Profile;
import com.thinkparity.model.profile.ProfileEMail;

/**
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class UpdateProfileAvatar extends Avatar {
    
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** The avatar model. */
    private final UpdateProfileAvatarModel model;

    /** Creates new form UpdateProfileAvatar */
    public UpdateProfileAvatar() {
        super("UpdateProfileAvatar");
        this.model = new UpdateProfileAvatarModel();
        bindEscapeKey("Cancel", new AbstractAction() {
            public void actionPerformed(final ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });
        initComponents();
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getId()
     * 
     */
    public AvatarId getId() {
        return AvatarId.DIALOG_PROFILE_UPDATE;
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#getState()
     * 
     */
    public State getState() {
        return null;
    }

    /**
     * @see com.thinkparity.codebase.swing.AbstractJPanel#isInputValid()
     */
    @Override
    public Boolean isInputValid() {
        final String name = extractInputName();
        final String organization = extractInputOrganization();
        final String title = extractInputTitle();
        if (null != name && null != organization && null != title) {
            return Boolean.TRUE;
        } else {
            return Boolean.FALSE;
        }
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#reload()
     */
    @Override
    public void reload() {
        final Profile  profile = readProfile();
        reloadName(profile);
        reloadOrganization(profile);
        reloadTitle(profile);
        reloadEmails(readProfileEmails());
        emailJTextField.requestFocusInWindow();
    }

    /**
     * @see com.thinkparity.browser.platform.application.display.avatar.Avatar#setState(com.thinkparity.browser.platform.util.State)
     * 
     */
    public void setState(final State state) {}

    private void addJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_addJButtonActionPerformed
        getController().runAddProfileEmail(extractInputEmail());
        emailJTextField.setText("");
        reloadEmails(readProfileEmails());
    }//GEN-LAST:event_addJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_cancelJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void emailJTextFieldActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_emailJTextFieldActionPerformed
        addJButtonActionPerformed(e);
    }//GEN-LAST:event_emailJTextFieldActionPerformed

    private void emailsJListMouseReleased(java.awt.event.MouseEvent e) {//GEN-FIRST:event_emailsJListMouseReleased
    }//GEN-LAST:event_emailsJListMouseReleased

    private EMail extractInputEmail() {
        return EMailBuilder.parse(SwingUtil.extract(emailJTextField));
    }

    private String extractInputName() {
        return SwingUtil.extract(nameJTextField);
    }

    private String extractInputOrganization() {
        return SwingUtil.extract(organizationJTextField);
    }

    private List<ProfileEMail> extractInputSelectedEmails() {
        return model.getSelectedEmails(emailsJList);
    }

    private String extractInputTitle() {
        return SwingUtil.extract(titleJTextField);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton addJButton;
        javax.swing.JButton cancelJButton;
        javax.swing.JLabel eaJLabel;
        javax.swing.JLabel emailsJLabel;
        javax.swing.JScrollPane emailsJScrollPane;
        javax.swing.JPanel innerJPanel;
        javax.swing.JSeparator jSeparator;
        javax.swing.JLabel nameJLabel;
        javax.swing.JLabel organizationJLabel;
        javax.swing.JButton removeJButton;
        javax.swing.JButton saveJButton;
        javax.swing.JLabel titleJLabel;
        javax.swing.JButton verifyJButton;

        innerJPanel = new javax.swing.JPanel();
        eaJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        organizationJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        organizationJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        titleJTextField = new javax.swing.JTextField();
        jSeparator = new javax.swing.JSeparator();
        emailsJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        emailsJScrollPane = new javax.swing.JScrollPane();
        emailsJList = new javax.swing.JList();
        verifyJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();

        setOpaque(false);
        innerJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.InnerPanelTitle")));
        innerJPanel.setOpaque(false);
        eaJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.EmbeddedAssistance"));

        nameJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.NameLabel"));

        organizationJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.OrganizationLabel"));

        titleJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.TitleLabel"));

        emailsJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.EmailsLabel"));

        emailJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                emailJTextFieldActionPerformed(e);
            }
        });

        addJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.AddEmailButton"));
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                addJButtonActionPerformed(e);
            }
        });

        emailsJList.setModel(model.getEmailsListModel());
        emailsJList.setCellRenderer(new ProfileEMailCellRenderer());
        emailsJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent e) {
                emailsJListMouseReleased(e);
            }
        });

        emailsJScrollPane.setViewportView(emailsJList);

        verifyJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.VerifyButton"));
        verifyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                verifyJButtonActionPerformed(e);
            }
        });

        removeJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.RemoveButton"));
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                removeJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout innerJPanelLayout = new org.jdesktop.layout.GroupLayout(innerJPanel);
        innerJPanel.setLayout(innerJPanelLayout);
        innerJPanelLayout.setHorizontalGroup(
            innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(emailsJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSeparator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
            .add(innerJPanelLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(eaJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap(69, Short.MAX_VALUE))
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameJLabel)
                    .add(organizationJLabel)
                    .add(titleJLabel))
                .add(13, 13, 13)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(emailsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, innerJPanelLayout.createSequentialGroup()
                        .add(emailJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addJButton))
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .add(organizationJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, innerJPanelLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .add(removeJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(verifyJButton)
                .addContainerGap())
        );
        innerJPanelLayout.setVerticalGroup(
            innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(innerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(eaJLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameJLabel)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(organizationJLabel)
                    .add(organizationJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleJLabel)
                    .add(titleJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailsJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addJButton)
                    .add(emailJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailsJScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(innerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(verifyJButton)
                    .add(removeJButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.SaveButton"));
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                saveJButtonActionPerformed(e);
            }
        });

        cancelJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("DIALOG_PROFILE_UPDATE.CancelButton"));
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, innerJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(cancelJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(innerJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveJButton)
                    .add(cancelJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Read the profile from the content provider.
     * 
     * @return A <code>Profile</code>.
     */
    private Profile readProfile() {
        return (Profile) ((CompositeFlatSingleContentProvider) contentProvider).getElement(0, null);
    }

    /**
     * Read the profile email addresses from the content provider.
     * 
     * @return A <code>List&lt;ProfileEMail&gt;</code>.
     */
    private List<ProfileEMail> readProfileEmails() {
        final List<ProfileEMail> profileEMails = new ArrayList<ProfileEMail>();
        final ProfileEMail[] array =
            (ProfileEMail[]) ((CompositeFlatSingleContentProvider) contentProvider).getElements(0, null);
        for (final ProfileEMail profileEMail : array) {
            profileEMails.add(profileEMail);
        }
        return profileEMails;
    }

    private void reloadEmails(final List<ProfileEMail> emails) {
        model.clear();
        for (final ProfileEMail email : emails) {
            model.add(toDisplay(email));
        }
    }

    private void reloadName(final Profile profile) {
        nameJTextField.setText("");
        final String name = profile.getName();
        if (null != name) {
            nameJTextField.setText(name);
        }
    }

    private void reloadOrganization(final Profile profile) {
        organizationJTextField.setText("");
        final String organization = profile.getOrganization();
        if (null != organization) {
            organizationJTextField.setText(organization);
        }
    }

    private void reloadTitle(final Profile profile) {
        titleJTextField.setText("");
        final String title = profile.getTitle();
        if (null != title) {
            titleJTextField.setText(title);
        }
    }

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_removeJButtonActionPerformed
        final List<ProfileEMail> selectedEmails = extractInputSelectedEmails();
        for (final ProfileEMail selectedEmail : selectedEmails) {
            getController().runRemoveProfileEmail(selectedEmail.getEmailId());
        }
        reloadEmails(readProfileEmails());
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_saveJButtonActionPerformed
        if (isInputValid()) {
            final String name = extractInputName();
            final String organization = extractInputOrganization();
            final String title = extractInputTitle();
            getController().runUpdateProfile(name, organization, title);
            disposeWindow();
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private ProfileEMailCell toDisplay(final ProfileEMail email) {
        final ProfileEMailCell display = new ProfileEMailCell();
        display.setEmail(email.getEmail());
        display.setEmailId(email.getEmailId());
        display.setProfileId(email.getProfileId());
        display.setVerified(email.isVerified());
        return display;
    }

    private void verifyJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_verifyJButtonActionPerformed
        final List<ProfileEMail> selectedEmails = extractInputSelectedEmails();
        for (final ProfileEMail selectedEmail : selectedEmails) {
            getController().runVerifyProfileEmail(selectedEmail.getEmailId());
        }
        reloadEmails(readProfileEmails());
    }//GEN-LAST:event_verifyJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JList emailsJList;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField organizationJTextField;
    private javax.swing.JTextField titleJTextField;
    // End of variables declaration//GEN-END:variables

}
