/*
 * SearchPartner.java
 *
 * Created on April 1, 2006, 11:28 AM
 */

package com.thinkparity.browser.application.browser.display.avatar.contact;

import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentListener;

import com.thinkparity.browser.application.browser.BrowserConstants;
import com.thinkparity.browser.application.browser.component.ButtonFactory;
import com.thinkparity.browser.application.browser.component.ListFactory;
import com.thinkparity.browser.application.browser.component.TextFactory;
import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.application.browser.display.avatar.session.ContactCellRenderer;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;

/**
 *
 * @author raykroeker@gmail.com
 */
public class SearchPartner extends Avatar {

    /**
     * @see java.io.Serializable
     *
     */
    private static final long serialVersionUID = 1;

    private DefaultListModel contactsModel;

    /**
     * Creates new form SearchPartner
     */
    public SearchPartner() {
        super("SearchPartner", BrowserConstants.DIALOGUE_BACKGROUND);
        initComponents();
    }

    /**
     * Set the avatar state.
     * 
     * 
     * @param state
     *            The avatar's state information.
     */
    public void setState(final State state) {}

    /**
     * Obtain the avatar's state information.
     * 
     * 
     * @return The avatar's state information.
     */
    public State getState() { return null; }

    /**
     * Obtain the avatar id.
     * 
     * 
     * @return The avatar id.
     */
    public AvatarId getId() { return AvatarId.SESSION_SEARCH_PARTNER; }

    public void reload() {
        reloadAddJButton();
        reloadSearchJButton();

        if(contactsJList.isSelectionEmpty()) {
            searchJButton.requestFocusInWindow();
        }
        else { addJButton.requestFocusInWindow(); }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton closeJButton;
        javax.swing.JScrollPane contactsJScrollPane;
        javax.swing.JTextArea eaJTextArea;
        javax.swing.JScrollPane jScrollPane1;
        javax.swing.JTextArea jTextArea1;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        contactsJScrollPane = new javax.swing.JScrollPane();
        contactsJList = ListFactory.create();
        searchJTextField = TextFactory.create();
        searchJButton = ButtonFactory.create(getString("SearchButton"));
        addJButton = ButtonFactory.create(getString("AddButton"));
        closeJButton = ButtonFactory.create(getString("CloseButton"));
        eaJTextArea = TextFactory.createArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        contactsModel = new DefaultListModel();
        contactsJList.setModel(contactsModel);
        contactsJList.setCellRenderer(new ContactCellRenderer());
        contactsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                contactsJListValueChanged(e);
            }
        });

        contactsJScrollPane.setViewportView(contactsJList);

        searchJTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(final javax.swing.event.DocumentEvent e) {
                searchJTextFieldInsertUpdate(e);
            }
            public void removeUpdate(final javax.swing.event.DocumentEvent e) {
                searchJTextFieldRemoveUpdate(e);
            }
            public void changedUpdate(final javax.swing.event.DocumentEvent e) {
                searchJTextFieldChangedUpdate(e);
            }
        });

        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                searchJButtonActionPerformed(e);
            }
        });

        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                addJButtonActionPerformed(e);
            }
        });

        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                closeJButtonActionPerformed(e);
            }
        });

        eaJTextArea.setColumns(20);
        eaJTextArea.setLineWrap(true);
        eaJTextArea.setRows(5);
        eaJTextArea.setWrapStyleWord(true);
        eaJTextArea.setOpaque(false);
        eaJTextArea.setText(getString("EmbeddedAssistance"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, eaJTextArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 357, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, contactsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .add(searchJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .add(closeJButton))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(addJButton)
                            .add(searchJButton))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(eaJTextArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchJButton)
                    .add(searchJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(contactsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .add(addJButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_closeJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void contactsJListValueChanged(javax.swing.event.ListSelectionEvent e) {//GEN-FIRST:event_contactsJListValueChanged
        reloadAddJButton();
    }//GEN-LAST:event_contactsJListValueChanged

    private void disposeWindow() {
        SwingUtilities.getWindowAncestor(this).dispose();
    }

    private void reloadSearchJButton() {
        searchJButton.setEnabled(0 < searchJTextField.getText().length());
    }

    private void reloadAddJButton() {
        addJButton.setEnabled(!contactsJList.isSelectionEmpty());
    }

    private void addJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_addJButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_addJButtonActionPerformed

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_searchJButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void searchJTextFieldInsertUpdate(final javax.swing.event.DocumentEvent e) {
        reloadSearchJButton();
    }

    private void searchJTextFieldChangedUpdate(final javax.swing.event.DocumentEvent e) {
        reloadSearchJButton();
    }

    private void searchJTextFieldRemoveUpdate(final javax.swing.event.DocumentEvent e) {
        reloadSearchJButton();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JList contactsJList;
    private javax.swing.JButton searchJButton;
    private javax.swing.JTextField searchJTextField;
    // End of variables declaration//GEN-END:variables
}
