/*
 * Jan 25, 2006
 */
package com.thinkparity.browser.platform.action;

/**
 * @author raykroeker@gmail.com
 * @version 1.1
 */
public enum ActionId {
	ARTIFACT_ACCEPT_KEY_REQUEST, ARTIFACT_APPLY_FLAG_SEEN,
	ARTIFACT_DECLINE_ALL_KEY_REQUESTS, ARTIFACT_DECLINE_KEY_REQUEST,
	ARTIFACT_REQUEST_KEY, DOCUMENT_CLOSE, DOCUMENT_CREATE, DOCUMENT_DELETE,
	DOCUMENT_OPEN, DOCUMENT_OPEN_VERSION, SESSION_ACCEPT_INVITATION,
	SESSION_ADD_CONTACT, SESSION_DECLINE_INVITATION, SESSION_SEND,
	SYSTEM_MESSAGE_DELETE
}
