/*
 * DemoErrorWindow.java
 *
 * Created on October 18, 2006, 1:13 PM
 */

package com.thinkparity.ophelia.browser.mode.demo;

import java.io.IOException;

import com.thinkparity.codebase.swing.AbstractJDialog;
import com.thinkparity.codebase.swing.AbstractJFrame;

import com.thinkparity.ophelia.model.script.Script;

import com.thinkparity.ophelia.browser.util.l2fprod.NativeSkin;

/**
 * <b>Title:</b>thinkParity OpheliaUI Demo Error Window<br>
 * <b>Description:</b><br>
 * 
 * @author raymond@thinkparity.com
 * @version 1.1.2.3
 */
public class DemoErrorWindow extends AbstractJDialog {
    
    /**
     * Create DemoErrorWindow.
     * 
     * @param owner
     *            An owner <code>AbstractJFrame</code>.
     */
    public DemoErrorWindow(final AbstractJFrame owner) {
        super(owner, Boolean.TRUE, null);
        initComponents();
        new NativeSkin().roundCorners(this);
        setLocation(calculateLocation());
    }

    void setScript(final Script script) {
        demoErrorPanel.setScript(script);
    }

    void reload() throws IOException {
        demoErrorPanel.reload();
    }

    void setError(final Throwable error) {
        demoErrorPanel.setError(error);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        demoErrorPanel = new com.thinkparity.ophelia.browser.mode.demo.DemoErrorPanel();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(demoErrorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(demoErrorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.thinkparity.ophelia.browser.mode.demo.DemoErrorPanel demoErrorPanel;
    // End of variables declaration//GEN-END:variables
}
