/*
 * DemoErrorWindow.java
 *
 * Created on October 18, 2006, 1:13 PM
 */

package com.thinkparity.ophelia.browser.mode.demo;

import java.io.IOException;

import com.thinkparity.codebase.swing.AbstractJFrame;
import com.thinkparity.ophelia.browser.util.l2fprod.NativeSkin;
import com.thinkparity.ophelia.model.script.Script;

/**
 *
 * @author  raymond
 */
public class DemoErrorWindow extends AbstractJFrame {
    
    /** Creates new form DemoErrorWindow */
    public DemoErrorWindow() {
        super(null);
        initComponents();
        new NativeSkin().roundCorners(this);
        setLocation(calculateLocation());
    }

    void setScript(final Script script) {
        demoErrorPanel.setScript(script);
    }

    void reload() throws IOException {
        demoErrorPanel.reload();
    }

    void setError(final Throwable error) {
        demoErrorPanel.setError(error);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        demoErrorPanel = new com.thinkparity.ophelia.browser.mode.demo.DemoErrorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(demoErrorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(demoErrorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoErrorWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.thinkparity.ophelia.browser.mode.demo.DemoErrorPanel demoErrorPanel;
    // End of variables declaration//GEN-END:variables
    
}
