/*
 * DemoErrorPanel.java
 *
 * Created on October 18, 2006, 1:14 PM
 */

package com.thinkparity.ophelia.browser.mode.demo;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.StringWriter;

import javax.swing.AbstractAction;

import com.thinkparity.codebase.swing.AbstractJPanel;
import com.thinkparity.ophelia.model.script.Script;

/**
 *
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class DemoErrorPanel extends AbstractJPanel {

    /** The error <code>Throwable</code>. */
    private Throwable error;

    /** The <code>Script</code> causing the error. */
    private Script script;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JTabbedPane errorJTabbedPane;
    private javax.swing.JTextArea errorJTextArea;
    private javax.swing.JTextArea scriptJTextArea;
    private javax.swing.JLabel scriptNameJLabel;
    // End of variables declaration//GEN-END:variables

    /** Creates new form DemoErrorPanel */
    public DemoErrorPanel() {
        bindEscapeKey("Close", new AbstractAction() {
            public void actionPerformed(final ActionEvent e) {
                closeJButtonActionPerformed(e);
            }
        });
        initComponents();
    }

    void reload() throws IOException {
        final java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("localization/Browser_Messages");
        errorJTabbedPane.setTitleAt(0, bundle.getString("DemoErrorPanel.errorJTabbedPane.title0"));
        errorJTabbedPane.setTitleAt(1, bundle.getString("DemoErrorPanel.scriptJTabbedPane.title1"));
        reloadScript();
        reloadError();
    }

    void setError(final Throwable error) {
        this.error = error;
    }
    
    void setScript(final Script script) {
        this.script = script;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JPanel errorJPanel;
        javax.swing.JScrollPane errorJScrollPane;
        javax.swing.JPanel scriptJPanel;
        javax.swing.JScrollPane scriptJScrollPane;

        scriptNameJLabel = new javax.swing.JLabel();
        errorJTabbedPane = new javax.swing.JTabbedPane();
        errorJPanel = new javax.swing.JPanel();
        errorJScrollPane = new javax.swing.JScrollPane();
        errorJTextArea = new javax.swing.JTextArea();
        scriptJPanel = new javax.swing.JPanel();
        scriptJScrollPane = new javax.swing.JScrollPane();
        scriptJTextArea = new javax.swing.JTextArea();
        closeJButton = new javax.swing.JButton();

        scriptNameJLabel.setText("!Script Name:!");

        errorJTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        errorJTextArea.setColumns(20);
        errorJTextArea.setRows(5);
        errorJScrollPane.setViewportView(errorJTextArea);

        org.jdesktop.layout.GroupLayout errorJPanelLayout = new org.jdesktop.layout.GroupLayout(errorJPanel);
        errorJPanel.setLayout(errorJPanelLayout);
        errorJPanelLayout.setHorizontalGroup(
            errorJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(errorJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        errorJPanelLayout.setVerticalGroup(
            errorJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(errorJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        errorJTabbedPane.addTab("tab2", errorJPanel);

        scriptJTextArea.setColumns(20);
        scriptJTextArea.setRows(5);
        scriptJScrollPane.setViewportView(scriptJTextArea);

        org.jdesktop.layout.GroupLayout scriptJPanelLayout = new org.jdesktop.layout.GroupLayout(scriptJPanel);
        scriptJPanel.setLayout(scriptJPanelLayout);
        scriptJPanelLayout.setHorizontalGroup(
            scriptJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scriptJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        scriptJPanelLayout.setVerticalGroup(
            scriptJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scriptJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        errorJTabbedPane.addTab("tab1", scriptJPanel);

        closeJButton.setText(java.util.ResourceBundle.getBundle("localization/Browser_Messages").getString("DemoErrorPanel.closeButton"));
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, errorJTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, scriptNameJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .add(closeJButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(scriptNameJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(errorJTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void reloadError() {
        errorJTextArea.setText("");
        if (null != error) {
            final StringWriter sw = new StringWriter();
            final PrintWriter pw = new PrintWriter(sw);
            error.printStackTrace(pw);
            errorJTextArea.setText(sw.toString());
        }
    }
    private void reloadScript() throws IOException {
        scriptNameJLabel.setText("");
        scriptJTextArea.setText("");
        if (null != script) {
            scriptNameJLabel.setText(script.getName());
            final InputStream stream = script.open();
            try {
                scriptJTextArea.read(new InputStreamReader(script.open()), null);
            } finally {
                stream.close();
            }
        }
    }
    
}
