/*
 * EditProfileAvatarEmailTabPanel.java
 *
 * Created on December 6, 2006, 2:07 PM
 */

package com.thinkparity.ophelia.browser.application.browser.display.avatar.dialog.profile;

import java.util.List;

import com.thinkparity.codebase.model.profile.Profile;
import com.thinkparity.codebase.model.profile.ProfileEMail;

import com.thinkparity.ophelia.browser.application.browser.Browser;


/**
 *
 * @author robert@thinkparity.com
 */
public class EditProfileAvatarEmailTabPanel extends EditProfileAvatarAbstractTabPanel {

    /** Creates new form EditProfileAvatarEmailTabPanel */
    public EditProfileAvatarEmailTabPanel(final Browser browser, final EditProfileAvatar editProfileAvatar, final String tabName) {
        super(browser, editProfileAvatar, tabName);
        initComponents();
    }
    
    /**
     * @see com.thinkparity.ophelia.browser.application.browser.display.avatar.dialog.profile.EditProfileAvatarAbstractTabPanel#reload(com.thinkparity.codebase.model.profile.Profile)
     */
    @Override
    protected void reload(final Profile profile) {
        reloadEmails(readProfileEmails());
    }
    
    /**
     * Reload emails.
     */
    private void reloadEmails(final List<ProfileEMail> profileEmails) {
        
    }
    
    /**
     * Read the profile email addresses from the content provider.
     * 
     * @return A <code>List&lt;ProfileEMail&gt;</code>.
     */
    private List<ProfileEMail> readProfileEmails() {
        final List<ProfileEMail> profileEMails = getAvatar().readEmails();
/*        for (final ProfileEMail profileEMail : array) {
            profileEMails.add(profileEMail);
        }*/
        return profileEMails;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        explanationJLabel = new javax.swing.JLabel();
        primaryEmailJLabel = new javax.swing.JLabel();
        primaryEmailJTextField = new javax.swing.JTextField();
        newEmailJLabel = new javax.swing.JLabel();
        newEmail1JTextField = new javax.swing.JTextField();
        newEmail1JButton = new javax.swing.JButton();
        newEmail2JLabel = new javax.swing.JLabel();
        newEmail2JTextField = new javax.swing.JTextField();
        newEmail2JButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("localization/JPanel_Messages"); // NOI18N
        explanationJLabel.setText(bundle.getString("EditProfileDialogEmailTabPanel.Explanation")); // NOI18N

        primaryEmailJLabel.setText(bundle.getString("EditProfileDialogEmailTabPanel.PrimaryEmail")); // NOI18N

        primaryEmailJTextField.setEditable(false);

        newEmailJLabel.setText(bundle.getString("EditProfileDialogEmailTabPanel.AlternateEmail")); // NOI18N

        newEmail1JButton.setText(bundle.getString("EditProfileDialogEmailTabPanel.Remove")); // NOI18N

        newEmail2JLabel.setText(bundle.getString("EditProfileDialogEmailTabPanel.NewEmail")); // NOI18N

        newEmail2JButton.setText(bundle.getString("EditProfileDialogEmailTabPanel.Add")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(explanationJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, newEmail2JLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, newEmailJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, primaryEmailJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(primaryEmailJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, newEmail2JTextField)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, newEmail1JTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(newEmail1JButton)
                                    .add(newEmail2JButton))))))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {newEmail1JButton, newEmail2JButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(explanationJLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(primaryEmailJLabel)
                    .add(primaryEmailJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newEmailJLabel)
                    .add(newEmail1JTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(newEmail1JButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newEmail2JLabel)
                    .add(newEmail2JTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(newEmail2JButton))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel explanationJLabel;
    private javax.swing.JButton newEmail1JButton;
    private javax.swing.JTextField newEmail1JTextField;
    private javax.swing.JButton newEmail2JButton;
    private javax.swing.JLabel newEmail2JLabel;
    private javax.swing.JTextField newEmail2JTextField;
    private javax.swing.JLabel newEmailJLabel;
    private javax.swing.JLabel primaryEmailJLabel;
    private javax.swing.JTextField primaryEmailJTextField;
    // End of variables declaration//GEN-END:variables

}
