/*
 * Created on August 29, 2006, 11:35 AM
 */
package com.thinkparity.ophelia.browser.application.browser.display.avatar.dialog.profile;

import com.thinkparity.codebase.swing.SwingUtil;


import com.thinkparity.ophelia.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.ophelia.browser.application.browser.display.provider.CompositeSingleContentProvider;
import com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.ophelia.browser.platform.util.State;
import com.thinkparity.ophelia.model.session.Credentials;

/**
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class ResetPasswordAvatar extends Avatar {
    
    /** Creates new form ResetPasswordAvatar */
    public ResetPasswordAvatar() {
        super(AvatarId.DIALOG_PROFILE_RESET_PASSWORD);
        initComponents();
    }

    /**
     * Obtain the avatar id.
     * 
     * 
     * @return The avatar id.
     */
    public AvatarId getId() {
        return AvatarId.DIALOG_PROFILE_RESET_PASSWORD;
    }

    /**
     * Obtain the avatar's state information.
     * 
     * 
     * @return The avatar's state information.
     */
    public State getState() {
        return null;
    }

    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#reload()
     */
    @Override
    public void reload() {
        reloadSecurityQuestion();
        reloadNewPassword(null);
    }

    /**
     * Set the avatar state.
     * 
     * 
     * @param state
     *            The avatar's state information.
     */
    public void setState(final State state) {}

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_cancelJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private String extractSecurityAnswer() {
        return SwingUtil.extract(securityAnswerJTextArea);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JButton cancelJButton;
        javax.swing.JLabel newPasswordJLabel;
        javax.swing.JButton resetJButton;
        javax.swing.JLabel securityAnswerJLabel;
        javax.swing.JScrollPane securityAnswerJScrollPane;
        javax.swing.JLabel securityQuestionJLabel;

        securityQuestionJLabel = new javax.swing.JLabel();
        securityQuestion2JLabel = new javax.swing.JLabel();
        securityAnswerJLabel = new javax.swing.JLabel();
        securityAnswerJScrollPane = new javax.swing.JScrollPane();
        securityAnswerJTextArea = new javax.swing.JTextArea();
        newPasswordJLabel = new javax.swing.JLabel();
        newPasswordJTextField = new javax.swing.JTextField();
        cancelJButton = new javax.swing.JButton();
        resetJButton = new javax.swing.JButton();

        securityQuestionJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DIALOG_PROFILE_RESET_PASSWORD.SecurityQuestionLabel"));

        securityAnswerJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DIALOG_PROFILE_RESET_PASSWORD.SecurityAnswerLabel"));

        securityAnswerJTextArea.setColumns(20);
        securityAnswerJTextArea.setFont(newPasswordJTextField.getFont());
        securityAnswerJTextArea.setRows(5);
        securityAnswerJScrollPane.setViewportView(securityAnswerJTextArea);

        newPasswordJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DIALOG_PROFILE_RESET_PASSWORD.NewPasswordLabel"));

        newPasswordJTextField.setEditable(false);

        cancelJButton.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DIALOG_PROFILE_RESET_PASSWORD.CancelButton"));
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cancelJButtonActionPerformed(e);
            }
        });

        resetJButton.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DIALOG_PROFILE_RESET_PASSWORD.ResetButton"));
        resetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                resetJButtonActionPerformed(e);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(securityAnswerJLabel)
                            .add(newPasswordJLabel)
                            .add(securityQuestionJLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, securityQuestion2JLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, securityAnswerJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .add(newPasswordJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cancelJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(resetJButton)
                        .add(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(securityQuestionJLabel)
                    .add(securityQuestion2JLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(securityAnswerJScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(securityAnswerJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newPasswordJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(newPasswordJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resetJButton)
                    .add(cancelJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private String readSecurityQuestion() {
        return (String) ((CompositeSingleContentProvider) contentProvider).getElement(0, null);
    }

    private Credentials readCredentials() {
        return (Credentials) ((CompositeSingleContentProvider) contentProvider).getElement(1, null);
    }

    private void reloadNewPassword(final Credentials credentials) {
        newPasswordJTextField.setText("");
        if (null != credentials) {
            newPasswordJTextField.setText(credentials.getPassword());
        }
    }

    private void reloadSecurityQuestion() {
        securityQuestion2JLabel.setText("");
        final String securityQuestion = readSecurityQuestion();
        if (null != securityQuestion) {
            securityQuestion2JLabel.setText(new StringBuffer("<html>")
                    .append(securityQuestion)
                    .append("</html>")
                    .toString());
        }
    }

    private void resetJButtonActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_resetJButtonActionPerformed
        final String securityAnswer = extractSecurityAnswer();
        if (null != securityAnswer) {
            getController().runResetProfilePassword(securityAnswer);
            reloadNewPassword(readCredentials());
        }
    }//GEN-LAST:event_resetJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField newPasswordJTextField;
    private javax.swing.JTextArea securityAnswerJTextArea;
    private javax.swing.JLabel securityQuestion2JLabel;
    // End of variables declaration//GEN-END:variables
}
