/*
 * ContactInfo.java
 *
 * Created on June 29, 2006, 5:47 PM
 */

package com.thinkparity.browser.application.browser.display.avatar.contact;

import javax.swing.SwingUtilities;

import com.thinkparity.browser.application.browser.BrowserConstants;
import com.thinkparity.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.browser.application.browser.display.provider.SingleContentProvider;
import com.thinkparity.browser.platform.action.Data;
import com.thinkparity.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.browser.platform.util.State;

import com.thinkparity.model.xmpp.JabberId;
import com.thinkparity.model.xmpp.contact.Contact;

/**
 *
 * @author  Administrator
 */
public class ContactInfo extends Avatar {
    
    /** Creates new form ContactInfo */
    public ContactInfo() {
        super("ContactInfo", BrowserConstants.DIALOGUE_BACKGROUND);
        initComponents();
        contactInfoJPanel.setBackground(BrowserConstants.DIALOGUE_BACKGROUND);
    }

    public void setState(final State state) {
    }

    public State getState() {
        return null;
    }
    
    /**
     * Obtain the contact.
     *
     * @return The contact.
     */
    private Contact getContact(JabberId contactId) {
        return (Contact) ((SingleContentProvider) contentProvider)
                .getElement((Object)contactId);
    }

    
    public void reload() {
        // Clear controls for contact name, company, and email
        nameJTextField.setText("");
        companyJTextField.setText("");
        emailJTextField.setText("");
        
        // Get the contact id from Data, populate controls to show
        // contact name, company and email
        JabberId id = getInputContactId();
        if (id != null) {
            Contact c = getContact(id);
            if (c != null) {
                nameJTextField.setText(c.getName());
                companyJTextField.setText(c.getOrganization());
                emailJTextField.setText(c.getEmail());
            }
        }
        
        closeJButton.requestFocusInWindow();
    }

    public AvatarId getId() {
        return AvatarId.CONTACT_INFO_DIALOGUE;
    }
    
    /**
     * Obtain the input contact id.
     *
     * @return A contact id.
     */
    private JabberId getInputContactId() {
        if (input!=null) {
            return (JabberId) ((Data) input).get(DataKey.CONTACT_ID);
        }
        else {
            return null;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        closeJButton = new javax.swing.JButton();
        contactInfoJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        companyJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        companyJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();

        closeJButton.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("ContactInfoDialog.Close"));
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        contactInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("ContactInfoDialog.BorderTitle")));
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("ContactInfoDialog.Name"));

        companyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        companyJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("ContactInfoDialog.Company"));

        emailJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailJLabel.setText(java.util.ResourceBundle.getBundle("com/thinkparity/browser/platform/util/l10n/JPanel_Messages").getString("ContactInfoDialog.Email"));

        nameJTextField.setEditable(false);
        nameJTextField.setFocusable(false);

        companyJTextField.setEditable(false);
        companyJTextField.setFocusable(false);

        emailJTextField.setEditable(false);
        emailJTextField.setFocusable(false);

        org.jdesktop.layout.GroupLayout contactInfoJPanelLayout = new org.jdesktop.layout.GroupLayout(contactInfoJPanel);
        contactInfoJPanel.setLayout(contactInfoJPanelLayout);
        contactInfoJPanelLayout.setHorizontalGroup(
            contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contactInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(companyJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(emailJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(nameJLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(companyJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .add(emailJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, contactInfoJPanelLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nameJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contactInfoJPanelLayout.setVerticalGroup(
            contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contactInfoJPanelLayout.createSequentialGroup()
                .add(contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(companyJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(companyJLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contactInfoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(emailJLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(contactInfoJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, closeJButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(contactInfoJPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeJButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_closeJButtonActionPerformed
    
    /**
     * Dispose of the window.
     */
    private void disposeWindow() {
        SwingUtilities.getWindowAncestor(this).dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel companyJLabel;
    private javax.swing.JTextField companyJTextField;
    private javax.swing.JPanel contactInfoJPanel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    // End of variables declaration//GEN-END:variables
    
    public enum DataKey { CONTACT_ID }
}
