select CI.CONTACT_INVITATION_ID "id",PUC.USERNAME "created by",
    CI.CREATED_ON "created on",PU.USERNAME "user",E.EMAIL "invitation e-mail"
from CONTACT_INVITATION_OUTGOING_EMAIL CIOE
    inner join CONTACT_INVITATION CI on CI.CONTACT_INVITATION_ID=CIOE.CONTACT_INVITATION_ID
    inner join PARITY_USER PUC on PUC.USER_ID=CI.CREATED_BY
    inner join PARITY_USER PU on PU.USER_ID=CIOE.USER_ID
    inner join EMAIL E on E.EMAIL_ID=CIOE.INVITATION_EMAIL_ID
order by CIOE.USER_ID asc,CI.CREATED_ON asc