select U.USERNAME,PR.RELEASE_NAME,PRE.ERROR_DATE,PRE.ERROR_XML from TPSD_PRODUCT_RELEASE_ERROR PRE
inner join TPSD_PRODUCT_RELEASE PR on PR.RELEASE_ID=PRE.RELEASE_ID
inner join TPSD_USER U on U.USER_ID=PRE.USER_ID
order by PR.RELEASE_ID desc,PRE.ERROR_DATE desc