select A.ARTIFACT_UNIQUE_ID "id",ADOU.USERNAME "draft owner",CBU.USERNAME "created by",CBU2.JABBER_ID "created by (backup)",A.CREATED_ON "created on",A2.CREATED_ON "created on (backup)"
from TPSD_ARTIFACT A
inner join TPSD_USER CBU on CBU.USER_ID=A.CREATED_BY
inner join TPSD_USER ADOU on ADOU.USER_ID=A.ARTIFACT_DRAFT_OWNER
inner join ARTIFACT A2 on A2.ARTIFACT_UNIQUE_ID=A.ARTIFACT_UNIQUE_ID
inner join PARITY_USER CBU2 on CBU2.USER_ID=A2.CREATED_BY
where A.ARTIFACT_UNIQUE_ID = 'f53ad80a-3792-4894-8ffa-bc91c15365d3'
order by A.CREATED_ON desc
