select CI.CONTACT_INVITATION_ID "id",PUC.USERNAME "created by",
    CI.CREATED_ON "created on",PU.USERNAME "user",E.EMAIL "e-mail",
    PUEB.USERNAME "extended by"
from CONTACT_INVITATION_INCOMING_EMAIL CIIE
    inner join CONTACT_INVITATION CI on CI.CONTACT_INVITATION_ID=CIIE.CONTACT_INVITATION_ID
    inner join PARITY_USER PUC on PUC.USER_ID=CI.CREATED_BY
    inner join PARITY_USER PU on PU.USER_ID=CIIE.USER_ID
    inner join EMAIL E on E.EMAIL_ID=CIIE.EMAIL_ID
    inner join PARITY_USER PUEB on PUEB.USER_ID=CIIE.EXTENDED_BY_USER_ID
order by CIIE.USER_ID asc,CI.CREATED_ON asc