select O.USERNAME "Owner",U.USERNAME,PPI.*
from TPSD_PAYMENT_PLAN PP 
    inner join TPSD_USER O on O.USER_ID=PP.PLAN_OWNER
    inner join TPSD_PAYMENT_PLAN_INVOICE PPI on PPI.PLAN_ID=PP.PLAN_ID
    inner join TPSD_USER_PAYMENT_PLAN UPP on UPP.PLAN_ID=PP.PLAN_ID
    inner join TPSD_USER U on U.USER_ID=UPP.USER_ID
where U.USERNAME='20071008-1404'
order by PP.PLAN_ID desc,PPI.INVOICE_ID desc;