select U.USER_ID "id",U.USERNAME "username",P.PRODUCT_NAME "product",PR.RELEASE_NAME "release",PR.RELEASE_OS "os"
from TPSD_USER U
inner join TPSD_USER_PRODUCT_RELEASE_REL UPRR on UPRR.USER_ID=U.USER_ID
inner join TPSD_PRODUCT P on P.PRODUCT_ID=UPRR.PRODUCT_ID
inner join TPSD_PRODUCT_RELEASE PR on PR.PRODUCT_ID=UPRR.PRODUCT_ID and PR.RELEASE_ID=UPRR.RELEASE_ID
order by U.USER_ID desc;