select O.USERNAME "Owner",U.USERNAME,PP.PLAN_ID,PP.PLAN_NAME,PP.PLAN_UNIQUE_ID,PC.CURRENCY_NAME,PP.PLAN_BILLABLE,PP.PLAN_ARREARS,PP.INVOICE_PERIOD,PP.INVOICE_PERIOD_OFFSET,PP.PLAN_PASSWORD
from TPSD_PAYMENT_PLAN PP 
    inner join TPSD_PAYMENT_CURRENCY PC on PC.CURRENCY_ID=PP.PLAN_CURRENCY
    inner join TPSD_USER O on O.USER_ID=PP.PLAN_OWNER
    inner join TPSD_USER_PAYMENT_PLAN UPP on UPP.PLAN_ID=PP.PLAN_ID    
    inner join TPSD_USER U on U.USER_ID=UPP.USER_ID
where U.USERNAME='ashaftoe'
order by PP.PLAN_ID desc;