select CI.CONTACT_INVITATION_ID "id",PUC.USERNAME "created by",
    CI.CREATED_ON "created on",PU.USER_ID "user id",PU.USERNAME "user",
    IU.USER_ID "invitation user id",IU.USERNAME "invitation user"
from CONTACT_INVITATION_OUTGOING_USER CIOU
    inner join CONTACT_INVITATION CI on CI.CONTACT_INVITATION_ID=CIOU.CONTACT_INVITATION_ID
    inner join PARITY_USER PUC on PUC.USER_ID=CI.CREATED_BY
    inner join PARITY_USER PU on PU.USER_ID=CIOU.USER_ID
    inner join PARITY_USER IU on IU.USER_ID=CIOU.INVITATION_USER_ID
order by CIOU.USER_ID asc,CI.CREATED_ON asc