select CI.CONTACT_INVITATION_ID "id",PUC.USERNAME "created by",
    CI.CREATED_ON "created on",PU.USERNAME "user",PUEB.USERNAME "extended by"
from TPSD_CONTACT_INVITATION_INCOMING_USER CIIU
    inner join TPSD_CONTACT_INVITATION CI on CI.CONTACT_INVITATION_ID=CIIU.CONTACT_INVITATION_ID
    inner join TPSD_USER PUC on PUC.USER_ID=CI.CREATED_BY
    inner join TPSD_USER PU on PU.USER_ID=CIIU.USER_ID
    inner join TPSD_USER PUEB on PUEB.USER_ID=CIIU.EXTENDED_BY_USER_ID
order by CIIU.USER_ID asc,CI.CREATED_ON asc