select A.ARTIFACT_UNIQUE_ID "id",A.ARTIFACT_NAME,CBU.NAME,A.CREATED_ON
from CONTAINER C
inner join ARTIFACT A on A.ARTIFACT_ID=C.CONTAINER_ID
inner join PARITY_USER CBU on CBU.USER_ID=A.CREATED_BY
order by A.CREATED_ON desc
