/*
 * ConfirmAvatar.java
 *
 * Created on January 23, 2007, 2:19 PM
 */

package com.thinkparity.ophelia.browser.application.browser.display.avatar.dialog;

import java.awt.event.ActionEvent;
import java.text.MessageFormat;

import javax.swing.AbstractAction;

import com.thinkparity.ophelia.browser.application.browser.BrowserConstants;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.ophelia.browser.platform.action.Data;
import com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.ophelia.browser.platform.util.State;

/**
 *
 * @author  user
 */
public class ConfirmAvatar extends Avatar {
    
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /** Flag indicating whether or not the user confirmed. */
    private Boolean confirm;
    
    /** Creates new form ConfirmAvatar */
    public ConfirmAvatar() {
        super("ConfirmDialog", BrowserConstants.DIALOGUE_BACKGROUND);
        bindEscapeKey("Cancel", new AbstractAction() {
            public void actionPerformed(final ActionEvent e) {
                disposeWindow();
            }
        });
        initComponents();
    }
    
    /**
     * Determine whether or not the user confirmed.
     * 
     * @return True if the user confirmed; false otherwise.
     */
    public Boolean didConfirm() {
        return confirm;
    }
    
    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#getAvatarTitle()
     */
    @Override
    public String getAvatarTitle() {
        if (null == input) {
            return null;
        } else if (null == getInputConfirmMessageKey()) {
            return getString("Title");
        } else {
            final StringBuffer confirmKey = new StringBuffer(getInputConfirmMessageKey()).append(".Title");
            return getString(confirmKey.toString());
        }
    }
    
    public AvatarId getId() { return AvatarId.DIALOG_CONFIRM; }

    public State getState() { return null; }
    
    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#reload()
     * 
     */
    public void reload() {
        confirm = Boolean.FALSE;
        reloadConfirmMessage();
    }

    public void setState(final State state) {}
    
    /**
     * Obtain a confirm message.
     * 
     * @return A confirm message <code>String</code>.
     */
    private String getInputLocalizedConfirmMessage() {
        if (null == input) {
            return null;
        } else {
            return (String) ((Data) input).get(DataKey.LOCALIZED_MESSAGE);
        }
    }

    /**
     * Obtain the confirmation arguments from the input data.
     * 
     * @return The confirmation message arguments.
     */
    private Object[] getInputConfirmMessageArguments() {
        if (null == input) {
            return null;
        } else {
            return (Object[]) ((Data) input).get(DataKey.MESSAGE_ARGUMENTS);
        }
    }

    /**
     * Obtain the confirmation message key from the input data.
     * 
     * @return The confirmation message key.
     */
    private String getInputConfirmMessageKey() {
        if (null == input) {
            return null;
        } else {
            return (String) ((Data) input).get(DataKey.MESSAGE_KEY);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        final javax.swing.JButton confirmJButton = new javax.swing.JButton();
        final javax.swing.JButton denyJButton = new javax.swing.JButton();

        confirmMessageJLabel.setFont(Fonts.DialogFont);
        confirmMessageJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        confirmJButton.setFont(Fonts.DialogButtonFont);
        confirmJButton.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("ConfirmDialog.Confirm"));
        confirmJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmJButtonActionPerformed(evt);
            }
        });

        denyJButton.setFont(Fonts.DialogButtonFont);
        denyJButton.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("ConfirmDialog.Deny"));
        denyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmMessageJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(denyJButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confirmJButton, denyJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(confirmMessageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denyJButton)
                    .addComponent(confirmJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void denyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyJButtonActionPerformed
        confirm = Boolean.FALSE;
        disposeWindow();
    }//GEN-LAST:event_denyJButtonActionPerformed

    private void confirmJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmJButtonActionPerformed
        confirm = Boolean.TRUE;
        disposeWindow();
    }//GEN-LAST:event_confirmJButtonActionPerformed
    
    /**
     * Reload the confirmation message.
     *
     */
    private void reloadConfirmMessage() {
        confirmMessageJLabel.setText("");
        final String localizedConfirmMessage = getInputLocalizedConfirmMessage();
        final String confirmMessageKey = getInputConfirmMessageKey();
        final Object[] confirmMessageArguments = getInputConfirmMessageArguments();
        if (null != localizedConfirmMessage) {
            confirmMessageJLabel.setText(MessageFormat.format("<html>{0}</html>", localizedConfirmMessage));
        } else if (null != confirmMessageKey) {
            final String text;
            if (null != confirmMessageArguments) {
                text = getString(confirmMessageKey, confirmMessageArguments);
            } else {
                text = getString(confirmMessageKey);
            }
            confirmMessageJLabel.setText(MessageFormat.format("<html>{0}</html>", text));
        }
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JLabel confirmMessageJLabel = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
    
    /** Data keys. */
    public enum DataKey { LOCALIZED_MESSAGE, MESSAGE_ARGUMENTS, MESSAGE_KEY }
}
