/*
 * Created on October 17, 2006, 3:30 PM
 */
package com.thinkparity.ophelia.browser.platform.firstrun;

import com.thinkparity.ophelia.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.ophelia.browser.platform.util.State;

/**
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class ConfirmSynchronizePanel extends Avatar {

    /** The <code>AvatarId</code>. */
    private static final AvatarId ID;

    static {
        ID = AvatarId.DIALOG_PLATFORM_CONFIRM_SYNCHRONIZE;
    }

    /** Whether or not the user confirmed. */
    private Boolean didConfirm;

    /** Create ConfirmSynchronize. */
    public ConfirmSynchronizePanel() {
        super(ID);
        initComponents();
    }

    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#getId()
     */
    @Override
    public AvatarId getId() {
        return ID;
    }

    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#getState()
     */
    @Override
    public State getState() {
        return null;
    }

    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#reload()
     */
    @Override
    public void reload() {
    }

    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#setState(com.thinkparity.ophelia.browser.platform.util.State)
     */
    @Override
    public void setState(final State state) {
    }

    Boolean didConfirm() {
        return didConfirm;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        confirmJLabel = new javax.swing.JLabel();
        yesJButton = new javax.swing.JButton();
        noJButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("localization/JPanel_Messages"); // NOI18N
        confirmJLabel.setText(bundle.getString("DIALOG_PLATFORM_CONFIRM_SYNCHRONIZE.confirmJLabel")); // NOI18N
        confirmJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        yesJButton.setText(bundle.getString("DIALOG_PLATFORM_CONFIRM_SYNCHRONIZE.yesJButton")); // NOI18N
        yesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesJButtonActionPerformed(evt);
            }
        });

        noJButton.setText(bundle.getString("DIALOG_PLATFORM_CONFIRM_SYNCHRONIZE.noJButton")); // NOI18N
        noJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, confirmJLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(noJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(yesJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(confirmJLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(yesJButton)
                    .add(noJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void noJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noJButtonActionPerformed
        didConfirm = Boolean.FALSE;
        disposeWindow();
    }//GEN-LAST:event_noJButtonActionPerformed

    private void yesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesJButtonActionPerformed
        didConfirm = Boolean.TRUE;
        disposeWindow();
    }//GEN-LAST:event_yesJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmJLabel;
    private javax.swing.JButton noJButton;
    private javax.swing.JButton yesJButton;
    // End of variables declaration//GEN-END:variables
}
