/*
 * Created On: July 31, 2006, 5:27 PM
 */
package com.thinkparity.ophelia.browser.application.browser.display.avatar;

import javax.swing.Icon;
import javax.swing.JLabel;

import com.thinkparity.codebase.assertion.Assert;
import com.thinkparity.codebase.model.profile.Profile;


import com.thinkparity.ophelia.browser.Constants.Icons.BrowserTitle;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.platform.action.Data;


/**
 * <b>Title:</b>thinkParity Main Title Tabs<br>
 * <b>Description:</b>The tabs in the title portion of the UI are a simple
 * panel with two images controlling the contexts.<br>
 * 
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class MainTitleAvatarTabPanel extends MainTitleAvatarAbstractPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** A thinkParity user's profile. */
    private Profile profile;

    /** The tab. */
    private MainTitleAvatar.Tab tab;

    /** Creates new form BrowserTitleTabs */
    public MainTitleAvatarTabPanel() {
        super();
        setResizeEdges(Resizer.FormLocation.LEFT);
        initComponents();
    }

    /**
     * Set localProfile.
     *
     * @param localProfile The Profile.
     */
    void setProfile(final Profile profile) {
        this.profile = profile;
        reloadDisplay();
    }

    /**
     * Select a tab.
     * 
     * @param tab
     *            A tab.
     */
    void setTab(final MainTitleAvatar.Tab tab) {
        this.tab = tab;
        reloadDisplay();
    }

    private void archiveJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_archiveJLabelMouseClicked
        selectTab(MainTitleAvatar.Tab.ARCHIVE);
    }//GEN-LAST:event_archiveJLabelMouseClicked

    private void archiveJLabelMouseEntered(java.awt.event.MouseEvent e) {//GEN-FIRST:event_archiveJLabelMouseEntered
        highlightTab(MainTitleAvatar.Tab.ARCHIVE, archiveJLabel, BrowserTitle.ARCHIVE_TAB_ROLLOVER);
    }//GEN-LAST:event_archiveJLabelMouseEntered

    private void archiveJLabelMouseExited(java.awt.event.MouseEvent e) {//GEN-FIRST:event_archiveJLabelMouseExited
        unhighlightTab(MainTitleAvatar.Tab.ARCHIVE, archiveJLabel, BrowserTitle.ARCHIVE_TAB);
    }//GEN-LAST:event_archiveJLabelMouseExited

    private void contactsJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_contactsJLabelMouseClicked
        selectTab(MainTitleAvatar.Tab.CONTACT);
    }//GEN-LAST:event_contactsJLabelMouseClicked

    private void contactsJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsJLabelMouseEntered
        highlightTab(MainTitleAvatar.Tab.CONTACT, contactsJLabel, BrowserTitle.CONTACTS_TAB_ROLLOVER);
    }//GEN-LAST:event_contactsJLabelMouseEntered

    private void contactsJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsJLabelMouseExited
        unhighlightTab(MainTitleAvatar.Tab.CONTACT, contactsJLabel, BrowserTitle.CONTACTS_TAB);
    }//GEN-LAST:event_contactsJLabelMouseExited

    private void containersJLabelMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_containersJLabelMouseClicked
        selectTab(MainTitleAvatar.Tab.CONTAINER);
    }//GEN-LAST:event_containersJLabelMouseClicked

    private void containersJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_containersJLabelMouseEntered
        highlightTab(MainTitleAvatar.Tab.CONTAINER, containersJLabel, BrowserTitle.CONTAINERS_TAB_ROLLOVER);
    }//GEN-LAST:event_containersJLabelMouseEntered

    private void containersJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_containersJLabelMouseExited
        unhighlightTab(MainTitleAvatar.Tab.CONTAINER, containersJLabel, BrowserTitle.CONTAINERS_TAB);
    }//GEN-LAST:event_containersJLabelMouseExited

    /**
     * Highlight a tab. If the tab is not selected; the label's icon will be
     * set to that provided.
     * 
     * @param tab
     *            A tab.
     * @param jLabel
     *            A <code>JLabel</code> representing the tab.
     * @param icon
     *            An <code>Icon</code>.
     * @see #unhighlightTab(com.thinkparity.ophelia.browser.application.browser.display.avatar.MainTitleAvatar.Tab,
     *      JLabel, Icon)
     */
    private void highlightTab(final MainTitleAvatar.Tab tab,
            final JLabel jLabel, final Icon icon) {
        if (this.tab != tab) {
            jLabel.setIcon(icon);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JLabel fillJLabel;
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel nameJLabel1;

        nameJLabel1 = new javax.swing.JLabel();
        containersJLabel = new javax.swing.JLabel();
        archiveJLabel = new javax.swing.JLabel();
        contactsJLabel = new javax.swing.JLabel();

        nameJLabel = new javax.swing.JLabel();
        fillJLabel = new javax.swing.JLabel();

        nameJLabel1.setFont(Fonts.DefaultFontBold);
        nameJLabel1.setMaximumSize(new java.awt.Dimension(100, 18));
        nameJLabel1.setMinimumSize(new java.awt.Dimension(100, 18));
        nameJLabel1.setPreferredSize(new java.awt.Dimension(100, 18));

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        containersJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ContainersTabSelected.png")));
        containersJLabel.setMaximumSize(new java.awt.Dimension(78, 20));
        containersJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                containersJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                containersJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                containersJLabelMouseExited(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(containersJLabel, gridBagConstraints);

        archiveJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ArchiveTab.png")));
        archiveJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archiveJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archiveJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archiveJLabelMouseExited(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(archiveJLabel, gridBagConstraints);

        contactsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_ContactsTab.png")));
        contactsJLabel.setMaximumSize(new java.awt.Dimension(78, 18));
        contactsJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactsJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactsJLabelMouseExited(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(contactsJLabel, gridBagConstraints);

        nameJLabel.setFont(Fonts.DefaultFontBold);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 2, 0);
        add(nameJLabel, gridBagConstraints);

        fillJLabel.setFont(Fonts.DefaultFontBold);
        fillJLabel.setMaximumSize(new java.awt.Dimension(100, 18));
        fillJLabel.setMinimumSize(new java.awt.Dimension(100, 18));
        fillJLabel.setPreferredSize(new java.awt.Dimension(100, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(fillJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    /**
     * Reload the display.  This will examine the current tab; then call the
     * controller to display the correct avatar; as well as update the images
     * representing the tabs.
     *
     */
    private void reloadDisplay() {
        reloadDisplayTab();
        reloadDisplayName();
    }

    /**
     * Reload the name label.
     * 
     */
    private void reloadDisplayName() {
        nameJLabel.setText("");
        if(null != profile) {
            nameJLabel.setText(profile.getName());
        }
    }

    /**
     * Reload the tab images; and display the correct avatar in the browser.
     * 
     */
    private void reloadDisplayTab() {
        switch(tab) {
        case ARCHIVE:
            archiveJLabel.setIcon(BrowserTitle.ARCHIVE_TAB_SELECTED);

            contactsJLabel.setIcon(BrowserTitle.CONTACTS_TAB);
            containersJLabel.setIcon(BrowserTitle.CONTAINERS_TAB);
            break;
        case CONTACT:
            contactsJLabel.setIcon(BrowserTitle.CONTACTS_TAB_SELECTED);

            archiveJLabel.setIcon(BrowserTitle.ARCHIVE_TAB);
            containersJLabel.setIcon(BrowserTitle.CONTAINERS_TAB);
            break;
        case CONTAINER:
            containersJLabel.setIcon(BrowserTitle.CONTAINERS_TAB_SELECTED);

            archiveJLabel.setIcon(BrowserTitle.ARCHIVE_TAB);
            contactsJLabel.setIcon(BrowserTitle.CONTACTS_TAB);
            break;
        default:
            Assert.assertUnreachable("UNKNOWN TAB");
        }
    }

    /**
     * Select a tab.  Here we set the input in the main title avatar to contain
     * the selected tab.
     * 
     * @param tab
     *            A tab.
     */
    private void selectTab(final MainTitleAvatar.Tab tab) {
        final Data data = (Data) ((Data) mainTitleAvatar.getInput()).clone();
        data.set(MainTitleAvatar.DataKey.TAB, tab);
        mainTitleAvatar.setInput(data);
    }

    /**
     * Unhighlight a tab. If the tab is not selected; the label's icon will be
     * set to that provided.
     * 
     * @param tab
     *            A tab.
     * @param jLabel
     *            A <code>JLabel</code> representing the tab.
     * @param icon
     *            An <code>Icon</code>.
     * @see #highlightTab(com.thinkparity.ophelia.browser.application.browser.display.avatar.MainTitleAvatar.Tab,
     *      JLabel, Icon)
     */
    private void unhighlightTab(final MainTitleAvatar.Tab tab,
            final JLabel jLabel, final Icon icon) {
        if (this.tab != tab) {
            jLabel.setIcon(icon);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel archiveJLabel;
    private javax.swing.JLabel contactsJLabel;
    private javax.swing.JLabel containersJLabel;
    private javax.swing.JLabel nameJLabel;
    // End of variables declaration//GEN-END:variables
}
