/*
 * Created On: July 31, 2006, 5:27 PM
 */
package com.thinkparity.ophelia.browser.application.browser.display.avatar;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

import javax.swing.Icon;
import javax.swing.JLabel;

import com.thinkparity.codebase.assertion.Assert;
import com.thinkparity.codebase.swing.SwingUtil;

import com.thinkparity.ophelia.browser.Constants.Colors;
import com.thinkparity.ophelia.browser.Constants.Icons.BrowserTitle;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.application.browser.component.LabelFactory;
import com.thinkparity.ophelia.browser.application.browser.display.avatar.MainTitleAvatar.TabId;
import com.thinkparity.ophelia.browser.application.browser.display.renderer.tab.TabButtonActionDelegate;


/**
 * <b>Title:</b>thinkParity Main Title Tabs<br>
 * <b>Description:</b>The tabs in the title portion of the UI are a simple
 * panel with two images controlling the contexts.<br>
 * 
 * @author raymond@thinkparity.com
 * @version 1.1.2.1
 */
public class MainTitleAvatarTabPanel extends MainTitleAvatarAbstractPanel {

    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;

    /** A resource bundle. */
    private static final ResourceBundle BUNDLE;

    static {
        BUNDLE = ResourceBundle.getBundle("localization/Browser_Messages");
    }

    /** A list of all core tabs. */
    private final Map<TabId, Tab> allTabs;

    /** The selected tab. */
    private Tab selectedTab;

    /** The tab button action delegate. */
    private TabButtonActionDelegate tabButtonActionDelegate;

    /** Creates new form BrowserTitleTabs */
    public MainTitleAvatarTabPanel() {
        super();
        this.allTabs = new HashMap<TabId, Tab>();
        initComponents();
        addMoveListener(this);
        new FocusHelper().addFocusListener(this);
        new Resizer(getBrowser(), this, Boolean.FALSE, Resizer.ResizeEdges.LEFT);
        new Resizer(getBrowser(), containerJLabel, Boolean.FALSE, Resizer.ResizeEdges.LEFT);
    }

    /**
     * @see javax.swing.JComponent#paintChildren(java.awt.Graphics)
     */
    @Override
    protected void paintChildren(final Graphics g) {
        super.paintChildren(g);
        final Graphics2D g2 = (Graphics2D) g.create();
        try {
            g2.setFont(Fonts.DefaultFontBold);
            for (final Tab tab : allTabs.values()) {
                tab.drawText(g2, g2.getFontMetrics());
            }
        } finally {
            g2.dispose();
        }
    }

    /**
     * Select a tab.
     * 
     * @param tabId
     *            A tab.
     */
    void selectTab(final TabId tabId) {
        this.selectedTab = allTabs.get(tabId);
        reloadDisplay();
        reloadTabButtonActionDelegate(tabId);
    }

    /**
     * Create a tab.
     * 
     * @param tabId
     *            An enumerated tab <code>TabId</code>.
     * @param leftmost
     *            Indicates if this is the leftmost tab.
     * @return A <code>Tab</code>.
     */
    private Tab createTab(final TabId tabId, final Boolean leftmost) {
        allTabs.put(tabId, new Tab(tabId, leftmost));
        return allTabs.get(tabId);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        containerJLabel = createTab(TabId.CONTAINER, Boolean.TRUE).jLabel;
        contactJLabel = createTab(TabId.CONTACT, Boolean.FALSE).jLabel;

        helpJLabel = createTab(TabId.HELP, Boolean.FALSE).jLabel;
        fillTopJLabel = new javax.swing.JLabel();
        fillRightJLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        containerJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_LeftmostTabSelected.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(containerJLabel, gridBagConstraints);

        contactJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_Tab.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(contactJLabel, gridBagConstraints);

        helpJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowserTitle_Tab.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(helpJLabel, gridBagConstraints);

        fillTopJLabel.setFont(Fonts.DefaultFontBold);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 2, 0);
        add(fillTopJLabel, gridBagConstraints);

        fillRightJLabel.setFont(Fonts.DefaultFontBold);
        fillRightJLabel.setMaximumSize(new java.awt.Dimension(100, 18));
        fillRightJLabel.setMinimumSize(new java.awt.Dimension(100, 18));
        fillRightJLabel.setPreferredSize(new java.awt.Dimension(100, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(fillRightJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    /**
     * Reload the action associated with the button.
     * 
     * @param tabId
     *            A <code>TabId</code>.
     */
    private void reloadTabButtonActionDelegate(final TabId tabId) {
        tabButtonActionDelegate = getBrowser().getTabButtonActionDelegate(tabId);
    }

    /**
     * Reload the display.
     */
    private void reloadDisplay() {
        for (final Tab tab : allTabs.values()) {
            tab.jLabel.setIcon(getTabIcon(selectedTab.isLeftmost(), Boolean.FALSE, Boolean.FALSE));
        }
        selectedTab.jLabel.setIcon(getTabIcon(selectedTab.isLeftmost(), Boolean.TRUE, Boolean.FALSE));
    }

    /**
     * Get the appropriate tab icon.
     * 
     * @param leftmost
     *            A <code>Boolean</code>, true for the leftmost tab.
     * @param selected
     *            A <code>Boolean</code>, true for the selected tab.
     * @param rollover
     *            A <code>Boolean</code>, true if the mouse is over the tab.
     */
    private Icon getTabIcon(final Boolean leftmost, final Boolean selected,
            final Boolean rollover) {
        final Icon icon;

        if (leftmost && selected) {
            icon = BrowserTitle.LEFTMOST_TAB_SELECTED;
        } else if (selected) {
            icon = BrowserTitle.TAB_SELECTED;
        } else if (rollover) {
            icon = BrowserTitle.TAB_ROLLOVER;
        } else {
            icon = BrowserTitle.TAB;  
        }

        return icon;
    }

    /**
     * Invoke the action associated with the tab button, if there is one.
     */
    private void invokeTabButtonAction() {
        Assert.assertNotNull("Null tab button action delegate in tab avatar.", tabButtonActionDelegate);
        if (tabButtonActionDelegate.isTabButtonActionAvailable()) {
            tabButtonActionDelegate.invokeForTabButton();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JLabel containerJLabel;
    private javax.swing.JLabel fillRightJLabel;
    private javax.swing.JLabel fillTopJLabel;
    private javax.swing.JLabel helpJLabel;
    // End of variables declaration//GEN-END:variables

    /** A tab definition. */
    private final class Tab {

        /** The action available <code>Boolean</code>. */
        private Boolean actionAvailable;

        /** The active <code>Rectangle</code>. */
        private final Rectangle activeRectangle;

        /** The tab label. */
        private final JLabel jLabel;

        /** The tab text. */
        private final String jLabelText;

        // Flag to indicate if this is the leftmost tab.
        private Boolean leftmost;

        /**
         * Create Tab.
         * 
         * @param tabId
         *            A tab id.
         * @param leftmost
         *            Indicate if this tab is the leftmost tab or not.
         */
        private Tab(final TabId tabId, final Boolean leftmost) {
            super();
            this.activeRectangle = new Rectangle();
            this.leftmost = leftmost;
            this.jLabel = LabelFactory.create(getTabIcon(leftmost, Boolean.FALSE, Boolean.FALSE));
            this.jLabelText = BUNDLE.getString(
                    new StringBuffer("MAIN_TITLE.MainTitleAvatar$TabId.")
                            .append(tabId).toString());
            this.jLabel.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(final MouseEvent e) {
                    if (!isSelectedTab()) {
                        getBrowser().selectTab(tabId);
                    } else if (isActionAvailable() && isInActiveRectangle(e.getPoint())) {
                        invokeTabButtonAction();
                    }
                }
                @Override
                public void mouseEntered(final MouseEvent e) {
                    if (isActionAvailable()) {
                        applyHandCursor(isInActiveRectangle(e.getPoint()));
                    }
                    jLabel.setIcon(getTabIcon(isLeftmost(), isSelectedTab(), Boolean.TRUE));
                }
                @Override
                public void mouseExited(final MouseEvent e) {
                    if (isActionAvailable()) {
                        applyHandCursor(Boolean.FALSE);
                    }
                    jLabel.setIcon(getTabIcon(isLeftmost(), isSelectedTab(), Boolean.FALSE));
                }
            });
            this.jLabel.addMouseMotionListener(new MouseAdapter() {
                @Override
                public void mouseMoved(final MouseEvent e) {
                    if (actionAvailable) {
                        applyHandCursor(isInActiveRectangle(e.getPoint()));
                    }
                }
            });
            final Dimension minimumSize = jLabel.getMinimumSize();
            minimumSize.height = 25;
            minimumSize.width = 77;
            this.jLabel.setMinimumSize(minimumSize);
        }       

        /**
         * Determine if this is the leftmost tab.
         * 
         * @return true if this is the leftmost tab.
         */
        public Boolean isLeftmost() {
            return leftmost;
        }

        /**
         * Apply or remove a hand cursor.
         * 
         * @param enable
         *            The enable <code>Boolean</code>.
         */
        private void applyHandCursor(final Boolean enable) {
            if (enable) {
                SwingUtil.setCursor(jLabel, java.awt.Cursor.HAND_CURSOR);
            } else {
                SwingUtil.setCursor(jLabel, null);
            }
        }

        /**
         * Draw the tab's text.
         * 
         * @param g2
         *            The <code>Graphics2D</code>.
         * @param fm
         *            The <code>FontMetrics</code>.
         */
        private void drawText(final Graphics2D g2, final FontMetrics fm) {
            final Point labelLocation = jLabel.getLocation();
            final Dimension labelSize = jLabel.getSize();
            final int textWidth = fm.stringWidth(jLabelText);
            final int textHeight = fm.getHeight();
            final int x = labelLocation.x + (labelSize.width - textWidth) / 2;
            final int y = labelLocation.y + (labelSize.height - textHeight) / 2 + 13;
            final Boolean actionAvailable = isActionAvailable();
            g2.setColor(actionAvailable ? Colors.Browser.Link.LINK_FOREGROUND : Color.BLACK);
            g2.drawString(jLabelText, x, y);
            // underline
            if (actionAvailable) {
                g2.drawLine(x, y + 2, x + fm.stringWidth(jLabelText), y + 2);
            }
            // set the active rectangle
            activeRectangle.setBounds(x, y-fm.getMaxAscent(), textWidth, textHeight);
        }

        /**
         * Determine if an action is available.
         * 
         * @return true if an action is available.
         */
        private Boolean isActionAvailable() {
            actionAvailable = isSelectedTab() && tabButtonActionDelegate.isTabButtonActionAvailable();
            return actionAvailable;
        }

        /**
         * Determine if the specified point is in the active rectangle.
         * 
         * @param point
         *            The <code>Point</code>.
         */
        private Boolean isInActiveRectangle(final Point point) {
            return SwingUtil.regionContains(activeRectangle, point);
        }

        /**
         * Determine if this is the selected tab.
         * 
         * @return true if this is the selected tab.
         */
        private Boolean isSelectedTab() {
            return this.equals(selectedTab);
        }
    }
}
