/*
 * DisplayInfoAvatar.java
 *
 * Created on October 9, 2006, 1:48 PM
 */

package com.thinkparity.ophelia.browser.application.browser.display.avatar.dialog;

import com.thinkparity.codebase.Application;
import com.thinkparity.codebase.StringUtil;
import com.thinkparity.codebase.swing.SwingUtil;

import com.thinkparity.codebase.model.util.http.Link;
import com.thinkparity.codebase.model.util.http.LinkFactory;

import com.thinkparity.ophelia.browser.BrowserException;
import com.thinkparity.ophelia.browser.Version;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants;
import com.thinkparity.ophelia.browser.application.browser.BrowserConstants.Fonts;
import com.thinkparity.ophelia.browser.application.browser.display.avatar.AvatarId;
import com.thinkparity.ophelia.browser.platform.BrowserPlatform;
import com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar;
import com.thinkparity.ophelia.browser.platform.util.State;

/**
 *
 * @author  Administrator
 */
public class DisplayInfoAvatar extends Avatar {
      
    /** @see java.io.Serializable */
    private static final long serialVersionUID = 1;
    
    /** An apache logger error statement. */
    private static final String LAUNCH_WEB_BROWSER_ERROR = "[LAUNCH WEB BROWSER ERROR]";
    
    /** Creates new form DisplayInfoAvatar */
    public DisplayInfoAvatar() {
        super("DisplayInfoAvatar", BrowserConstants.DIALOGUE_BACKGROUND);
        initComponents();
        initVersionJLabel();
        initBuildJLabel();
        initWebPageJLabel();
    }
    
    public void setState(final State state) {
    }

    public State getState() {
        return null;
    }

    public AvatarId getId() {
        return AvatarId.DIALOG_PLATFORM_DISPLAY_INFO;
    }
       
    /**
     * @see com.thinkparity.ophelia.browser.platform.application.display.avatar.Avatar#isAvatarTitle()
     */
    @Override
    public Boolean isAvatarTitle() {
        return Boolean.FALSE;
    }

    @Override
    public void installResizer() {
        // Don't install the resizer on the about dialog.
    }

    private void initVersionJLabel() {
        versionJLabel.setText(getString("Version", new Object[] { Version.getVersion() }));
    }
    
    private void initBuildJLabel() {
        buildJLabel.setText(getString("Build", new Object[] { Version.getBuildId() }));
    }
    
    private void initWebPageJLabel() {
        webPageJLabel.setText(getString("WebPage", new Object[] {getWebPageString()}));
    }
    
    private Link getWebPage() {
        return LinkFactory.getInstance(Application.OPHELIA, BrowserPlatform.getInstance().getEnvironment()).create();
    }

    private String getWebPageString() {
        // Strip off "http:/"
        return StringUtil.removeBefore(getWebPage().toString(), "//");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoJLabel = new javax.swing.JLabel();
        versionJLabel = new javax.swing.JLabel();
        buildJLabel = new javax.swing.JLabel();
        copyrightJLabel = new javax.swing.JLabel();
        fillLeftJLabel = new javax.swing.JLabel();
        webPageJLabel = new javax.swing.JLabel();
        fillRightJLabel = new javax.swing.JLabel();
        okJButton = new javax.swing.JButton();
        fillBottomLeftJLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        logoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thinkParityLogo.png")));
        logoJLabel.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(logoJLabel, gridBagConstraints);

        versionJLabel.setFont(Fonts.DialogFontBold);
        versionJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DisplayInfoAvatar.Version"));
        versionJLabel.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 15, 0, 15);
        add(versionJLabel, gridBagConstraints);

        buildJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DisplayInfoAvatar.Build"));
        buildJLabel.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 15, 0, 15);
        add(buildJLabel, gridBagConstraints);

        copyrightJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DisplayInfoAvatar.Copyright"));
        copyrightJLabel.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 15, 0, 15);
        add(copyrightJLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(fillLeftJLabel, gridBagConstraints);

        webPageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webPageJLabel.setText(java.util.ResourceBundle.getBundle("localization/JPanel_Messages").getString("DisplayInfoAvatar.ExampleWebPage"));
        webPageJLabel.setFocusable(false);
        webPageJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        webPageJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webPageJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webPageJLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                webPageJLabelMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        add(webPageJLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        add(fillRightJLabel, gridBagConstraints);

        okJButton.setText("OK");
        okJButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        add(okJButton, gridBagConstraints);

        fillBottomLeftJLabel.setPreferredSize(new java.awt.Dimension(65, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        add(fillBottomLeftJLabel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void webPageJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webPageJLabelMousePressed
        try {
            String runString = "rundll32 url.dll,FileProtocolHandler " + getWebPage().toString();
            Runtime.getRuntime().exec(runString);
        } catch (final Throwable t) {
            throw new BrowserException(LAUNCH_WEB_BROWSER_ERROR, t);            
        }
    }//GEN-LAST:event_webPageJLabelMousePressed

    private void webPageJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webPageJLabelMouseExited
        webPageJLabel.setText(getString("WebPage", new Object[] {getWebPageString()}));
        SwingUtil.setCursor((javax.swing.JLabel) evt.getSource(), java.awt.Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_webPageJLabelMouseExited

    private void webPageJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webPageJLabelMouseEntered
        webPageJLabel.setText(getString("WebPageHighlighted", new Object[] {getWebPageString()}));
        SwingUtil.setCursor((javax.swing.JLabel) evt.getSource(), java.awt.Cursor.HAND_CURSOR);
    }//GEN-LAST:event_webPageJLabelMouseEntered

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        disposeWindow();
    }//GEN-LAST:event_okJButtonActionPerformed
    
/*    Runtime rt = Runtime.getRuntime();
    rt.exec ( "start http://www.memi.umss.edu.bo/progra/" )*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildJLabel;
    private javax.swing.JLabel copyrightJLabel;
    private javax.swing.JLabel fillBottomLeftJLabel;
    private javax.swing.JLabel fillLeftJLabel;
    private javax.swing.JLabel fillRightJLabel;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JButton okJButton;
    private javax.swing.JLabel versionJLabel;
    private javax.swing.JLabel webPageJLabel;
    // End of variables declaration//GEN-END:variables
    
}
