/*
 * Jan 25, 2006
 */
package com.thinkparity.browser.platform.action;

/**
 * @author raykroeker@gmail.com
 * @version 1.1
 */
public enum ActionId {
    ADD_TEAM_MEMBER, APPLICATION_QUIT, ARTIFACT_ACCEPT_KEY_REQUEST,
    ARTIFACT_APPLY_FLAG_SEEN, ARTIFACT_DECLINE_ALL_KEY_REQUESTS,
    ARTIFACT_DECLINE_KEY_REQUEST, ARTIFACT_KEY_REQUESTED, ARTIFACT_REQUEST_KEY,
    ARTIFACT_SEARCH, ARTIFACT_SEND_VERSION, CREATE_DOCUMENTS, DOCUMENT_CLOSE,
    DOCUMENT_CREATE, DOCUMENT_DELETE, DOCUMENT_OPEN, DOCUMENT_OPEN_VERSION,
    DOCUMENT_REACTIVATE, DOCUMENT_RENAME, DOCUMENT_SEND_KEY,
    MOVE_BROWSER_TO_FRONT, PLATFORM_LOGIN, PLATFORM_LOGOUT, PLATFORM_QUIT,
    PLATFORM_RESTART, PLATFORM_SAVE_PROFILE, PUBLISH_DOCUMENT, RESTORE_BROWSER,
    SESSION_ACCEPT_INVITATION, SESSION_DECLINE_INVITATION, SESSION_SEND,
    SYSTEM_MESSAGE_DELETE
}
