/*
 * Jan 25, 2006
 */
package com.thinkparity.browser.platform.action;

/**
 * @author raykroeker@gmail.com
 * @version 1.1
 */
public enum ActionId {
    ADD_TEAM_MEMBER, APPLICATION_QUIT, ARTIFACT_APPLY_FLAG_SEEN, ARTIFACT_SEARCH, CONTACT_ADD,
    CONTACT_DELETE, CONTACT_OPEN, CONTAINER_CREATE,
    CONTAINER_PUBLISH,
    CREATE_DRAFT, CONTAINER_ADD_DOCUMENT,
    DOCUMENT_DELETE, DOCUMENT_OPEN, DOCUMENT_OPEN_VERSION,
    DOCUMENT_RENAME, DOCUMENT_UPDATE_DRAFT, MANAGE_TEAM,
    MOVE_BROWSER_TO_FRONT, PLATFORM_LOGIN, PLATFORM_LOGOUT, PLATFORM_QUIT,
    PLATFORM_RESTART, PLATFORM_SAVE_PROFILE, RESTORE_BROWSER,
    SESSION_ACCEPT_INVITATION, SESSION_DECLINE_INVITATION, SESSION_SEND,
    SYSTEM_MESSAGE_DELETE
}
